// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	UpepAccessions      string
	UpepBlastDB         string
	UpepCodon           string
	UpepFeatures        string
	UpepGeneIdentifiers string
	UpepMolecularTypes  string
	UpepOrganisms       string
	UpepRefSeqDB        string
	UpepRefSeqEntries   string
	UpepSorfPos         string
}{
	UpepAccessions:      "upep_accessions",
	UpepBlastDB:         "upep_blast_db",
	UpepCodon:           "upep_codon",
	UpepFeatures:        "upep_features",
	UpepGeneIdentifiers: "upep_gene_identifiers",
	UpepMolecularTypes:  "upep_molecular_types",
	UpepOrganisms:       "upep_organisms",
	UpepRefSeqDB:        "upep_ref_seq_db",
	UpepRefSeqEntries:   "upep_ref_seq_entries",
	UpepSorfPos:         "upep_sorf_pos",
}
