// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"reflect"
	"testing"

	"github.com/volatiletech/sqlboiler/boil"
	"github.com/volatiletech/sqlboiler/randomize"
	"github.com/volatiletech/sqlboiler/strmangle"
)

func testUpepRefSeqDBS(t *testing.T) {
	t.Parallel()

	query := UpepRefSeqDBS(nil)

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}
func testUpepRefSeqDBSDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	upepRefSeqDB := &UpepRefSeqDB{}
	if err = randomize.Struct(seed, upepRefSeqDB, upepRefSeqDBDBTypes, true, upepRefSeqDBColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UpepRefSeqDB struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = upepRefSeqDB.Insert(tx); err != nil {
		t.Error(err)
	}

	if err = upepRefSeqDB.Delete(tx); err != nil {
		t.Error(err)
	}

	count, err := UpepRefSeqDBS(tx).Count()
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testUpepRefSeqDBSQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	upepRefSeqDB := &UpepRefSeqDB{}
	if err = randomize.Struct(seed, upepRefSeqDB, upepRefSeqDBDBTypes, true, upepRefSeqDBColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UpepRefSeqDB struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = upepRefSeqDB.Insert(tx); err != nil {
		t.Error(err)
	}

	if err = UpepRefSeqDBS(tx).DeleteAll(); err != nil {
		t.Error(err)
	}

	count, err := UpepRefSeqDBS(tx).Count()
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testUpepRefSeqDBSSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	upepRefSeqDB := &UpepRefSeqDB{}
	if err = randomize.Struct(seed, upepRefSeqDB, upepRefSeqDBDBTypes, true, upepRefSeqDBColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UpepRefSeqDB struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = upepRefSeqDB.Insert(tx); err != nil {
		t.Error(err)
	}

	slice := UpepRefSeqDBSlice{upepRefSeqDB}

	if err = slice.DeleteAll(tx); err != nil {
		t.Error(err)
	}

	count, err := UpepRefSeqDBS(tx).Count()
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}
func testUpepRefSeqDBSExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	upepRefSeqDB := &UpepRefSeqDB{}
	if err = randomize.Struct(seed, upepRefSeqDB, upepRefSeqDBDBTypes, true, upepRefSeqDBColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UpepRefSeqDB struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = upepRefSeqDB.Insert(tx); err != nil {
		t.Error(err)
	}

	e, err := UpepRefSeqDBExists(tx, upepRefSeqDB.ID)
	if err != nil {
		t.Errorf("Unable to check if UpepRefSeqDB exists: %s", err)
	}
	if !e {
		t.Errorf("Expected UpepRefSeqDBExistsG to return true, but got false.")
	}
}
func testUpepRefSeqDBSFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	upepRefSeqDB := &UpepRefSeqDB{}
	if err = randomize.Struct(seed, upepRefSeqDB, upepRefSeqDBDBTypes, true, upepRefSeqDBColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UpepRefSeqDB struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = upepRefSeqDB.Insert(tx); err != nil {
		t.Error(err)
	}

	upepRefSeqDBFound, err := FindUpepRefSeqDB(tx, upepRefSeqDB.ID)
	if err != nil {
		t.Error(err)
	}

	if upepRefSeqDBFound == nil {
		t.Error("want a record, got nil")
	}
}
func testUpepRefSeqDBSBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	upepRefSeqDB := &UpepRefSeqDB{}
	if err = randomize.Struct(seed, upepRefSeqDB, upepRefSeqDBDBTypes, true, upepRefSeqDBColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UpepRefSeqDB struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = upepRefSeqDB.Insert(tx); err != nil {
		t.Error(err)
	}

	if err = UpepRefSeqDBS(tx).Bind(upepRefSeqDB); err != nil {
		t.Error(err)
	}
}

func testUpepRefSeqDBSOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	upepRefSeqDB := &UpepRefSeqDB{}
	if err = randomize.Struct(seed, upepRefSeqDB, upepRefSeqDBDBTypes, true, upepRefSeqDBColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UpepRefSeqDB struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = upepRefSeqDB.Insert(tx); err != nil {
		t.Error(err)
	}

	if x, err := UpepRefSeqDBS(tx).One(); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testUpepRefSeqDBSAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	upepRefSeqDBOne := &UpepRefSeqDB{}
	upepRefSeqDBTwo := &UpepRefSeqDB{}
	if err = randomize.Struct(seed, upepRefSeqDBOne, upepRefSeqDBDBTypes, false, upepRefSeqDBColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UpepRefSeqDB struct: %s", err)
	}
	if err = randomize.Struct(seed, upepRefSeqDBTwo, upepRefSeqDBDBTypes, false, upepRefSeqDBColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UpepRefSeqDB struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = upepRefSeqDBOne.Insert(tx); err != nil {
		t.Error(err)
	}
	if err = upepRefSeqDBTwo.Insert(tx); err != nil {
		t.Error(err)
	}

	slice, err := UpepRefSeqDBS(tx).All()
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testUpepRefSeqDBSCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	upepRefSeqDBOne := &UpepRefSeqDB{}
	upepRefSeqDBTwo := &UpepRefSeqDB{}
	if err = randomize.Struct(seed, upepRefSeqDBOne, upepRefSeqDBDBTypes, false, upepRefSeqDBColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UpepRefSeqDB struct: %s", err)
	}
	if err = randomize.Struct(seed, upepRefSeqDBTwo, upepRefSeqDBDBTypes, false, upepRefSeqDBColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UpepRefSeqDB struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = upepRefSeqDBOne.Insert(tx); err != nil {
		t.Error(err)
	}
	if err = upepRefSeqDBTwo.Insert(tx); err != nil {
		t.Error(err)
	}

	count, err := UpepRefSeqDBS(tx).Count()
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}
func upepRefSeqDBBeforeInsertHook(e boil.Executor, o *UpepRefSeqDB) error {
	*o = UpepRefSeqDB{}
	return nil
}

func upepRefSeqDBAfterInsertHook(e boil.Executor, o *UpepRefSeqDB) error {
	*o = UpepRefSeqDB{}
	return nil
}

func upepRefSeqDBAfterSelectHook(e boil.Executor, o *UpepRefSeqDB) error {
	*o = UpepRefSeqDB{}
	return nil
}

func upepRefSeqDBBeforeUpdateHook(e boil.Executor, o *UpepRefSeqDB) error {
	*o = UpepRefSeqDB{}
	return nil
}

func upepRefSeqDBAfterUpdateHook(e boil.Executor, o *UpepRefSeqDB) error {
	*o = UpepRefSeqDB{}
	return nil
}

func upepRefSeqDBBeforeDeleteHook(e boil.Executor, o *UpepRefSeqDB) error {
	*o = UpepRefSeqDB{}
	return nil
}

func upepRefSeqDBAfterDeleteHook(e boil.Executor, o *UpepRefSeqDB) error {
	*o = UpepRefSeqDB{}
	return nil
}

func upepRefSeqDBBeforeUpsertHook(e boil.Executor, o *UpepRefSeqDB) error {
	*o = UpepRefSeqDB{}
	return nil
}

func upepRefSeqDBAfterUpsertHook(e boil.Executor, o *UpepRefSeqDB) error {
	*o = UpepRefSeqDB{}
	return nil
}

func testUpepRefSeqDBSHooks(t *testing.T) {
	t.Parallel()

	var err error

	empty := &UpepRefSeqDB{}
	o := &UpepRefSeqDB{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, upepRefSeqDBDBTypes, false); err != nil {
		t.Errorf("Unable to randomize UpepRefSeqDB object: %s", err)
	}

	AddUpepRefSeqDBHook(boil.BeforeInsertHook, upepRefSeqDBBeforeInsertHook)
	if err = o.doBeforeInsertHooks(nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	upepRefSeqDBBeforeInsertHooks = []UpepRefSeqDBHook{}

	AddUpepRefSeqDBHook(boil.AfterInsertHook, upepRefSeqDBAfterInsertHook)
	if err = o.doAfterInsertHooks(nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	upepRefSeqDBAfterInsertHooks = []UpepRefSeqDBHook{}

	AddUpepRefSeqDBHook(boil.AfterSelectHook, upepRefSeqDBAfterSelectHook)
	if err = o.doAfterSelectHooks(nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	upepRefSeqDBAfterSelectHooks = []UpepRefSeqDBHook{}

	AddUpepRefSeqDBHook(boil.BeforeUpdateHook, upepRefSeqDBBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	upepRefSeqDBBeforeUpdateHooks = []UpepRefSeqDBHook{}

	AddUpepRefSeqDBHook(boil.AfterUpdateHook, upepRefSeqDBAfterUpdateHook)
	if err = o.doAfterUpdateHooks(nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	upepRefSeqDBAfterUpdateHooks = []UpepRefSeqDBHook{}

	AddUpepRefSeqDBHook(boil.BeforeDeleteHook, upepRefSeqDBBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	upepRefSeqDBBeforeDeleteHooks = []UpepRefSeqDBHook{}

	AddUpepRefSeqDBHook(boil.AfterDeleteHook, upepRefSeqDBAfterDeleteHook)
	if err = o.doAfterDeleteHooks(nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	upepRefSeqDBAfterDeleteHooks = []UpepRefSeqDBHook{}

	AddUpepRefSeqDBHook(boil.BeforeUpsertHook, upepRefSeqDBBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	upepRefSeqDBBeforeUpsertHooks = []UpepRefSeqDBHook{}

	AddUpepRefSeqDBHook(boil.AfterUpsertHook, upepRefSeqDBAfterUpsertHook)
	if err = o.doAfterUpsertHooks(nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	upepRefSeqDBAfterUpsertHooks = []UpepRefSeqDBHook{}
}
func testUpepRefSeqDBSInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	upepRefSeqDB := &UpepRefSeqDB{}
	if err = randomize.Struct(seed, upepRefSeqDB, upepRefSeqDBDBTypes, true, upepRefSeqDBColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UpepRefSeqDB struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = upepRefSeqDB.Insert(tx); err != nil {
		t.Error(err)
	}

	count, err := UpepRefSeqDBS(tx).Count()
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testUpepRefSeqDBSInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	upepRefSeqDB := &UpepRefSeqDB{}
	if err = randomize.Struct(seed, upepRefSeqDB, upepRefSeqDBDBTypes, true); err != nil {
		t.Errorf("Unable to randomize UpepRefSeqDB struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = upepRefSeqDB.Insert(tx, upepRefSeqDBColumnsWithoutDefault...); err != nil {
		t.Error(err)
	}

	count, err := UpepRefSeqDBS(tx).Count()
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testUpepRefSeqDBToManyRefSeqDBUpepRefSeqEntries(t *testing.T) {
	var err error
	tx := MustTx(boil.Begin())
	defer tx.Rollback()

	var a UpepRefSeqDB
	var b, c UpepRefSeqEntry

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, upepRefSeqDBDBTypes, true, upepRefSeqDBColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UpepRefSeqDB struct: %s", err)
	}

	if err := a.Insert(tx); err != nil {
		t.Fatal(err)
	}

	randomize.Struct(seed, &b, upepRefSeqEntryDBTypes, false, upepRefSeqEntryColumnsWithDefault...)
	randomize.Struct(seed, &c, upepRefSeqEntryDBTypes, false, upepRefSeqEntryColumnsWithDefault...)

	b.RefSeqDBID.Valid = true
	c.RefSeqDBID.Valid = true
	b.RefSeqDBID.Int64 = a.ID
	c.RefSeqDBID.Int64 = a.ID
	if err = b.Insert(tx); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(tx); err != nil {
		t.Fatal(err)
	}

	upepRefSeqEntry, err := a.RefSeqDBUpepRefSeqEntries(tx).All()
	if err != nil {
		t.Fatal(err)
	}

	bFound, cFound := false, false
	for _, v := range upepRefSeqEntry {
		if v.RefSeqDBID.Int64 == b.RefSeqDBID.Int64 {
			bFound = true
		}
		if v.RefSeqDBID.Int64 == c.RefSeqDBID.Int64 {
			cFound = true
		}
	}

	if !bFound {
		t.Error("expected to find b")
	}
	if !cFound {
		t.Error("expected to find c")
	}

	slice := UpepRefSeqDBSlice{&a}
	if err = a.L.LoadRefSeqDBUpepRefSeqEntries(tx, false, (*[]*UpepRefSeqDB)(&slice)); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.RefSeqDBUpepRefSeqEntries); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	a.R.RefSeqDBUpepRefSeqEntries = nil
	if err = a.L.LoadRefSeqDBUpepRefSeqEntries(tx, true, &a); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.RefSeqDBUpepRefSeqEntries); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	if t.Failed() {
		t.Logf("%#v", upepRefSeqEntry)
	}
}

func testUpepRefSeqDBToManyAddOpRefSeqDBUpepRefSeqEntries(t *testing.T) {
	var err error

	tx := MustTx(boil.Begin())
	defer tx.Rollback()

	var a UpepRefSeqDB
	var b, c, d, e UpepRefSeqEntry

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, upepRefSeqDBDBTypes, false, strmangle.SetComplement(upepRefSeqDBPrimaryKeyColumns, upepRefSeqDBColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*UpepRefSeqEntry{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, upepRefSeqEntryDBTypes, false, strmangle.SetComplement(upepRefSeqEntryPrimaryKeyColumns, upepRefSeqEntryColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err := a.Insert(tx); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(tx); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(tx); err != nil {
		t.Fatal(err)
	}

	foreignersSplitByInsertion := [][]*UpepRefSeqEntry{
		{&b, &c},
		{&d, &e},
	}

	for i, x := range foreignersSplitByInsertion {
		err = a.AddRefSeqDBUpepRefSeqEntries(tx, i != 0, x...)
		if err != nil {
			t.Fatal(err)
		}

		first := x[0]
		second := x[1]

		if a.ID != first.RefSeqDBID.Int64 {
			t.Error("foreign key was wrong value", a.ID, first.RefSeqDBID.Int64)
		}
		if a.ID != second.RefSeqDBID.Int64 {
			t.Error("foreign key was wrong value", a.ID, second.RefSeqDBID.Int64)
		}

		if first.R.RefSeqDB != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}
		if second.R.RefSeqDB != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}

		if a.R.RefSeqDBUpepRefSeqEntries[i*2] != first {
			t.Error("relationship struct slice not set to correct value")
		}
		if a.R.RefSeqDBUpepRefSeqEntries[i*2+1] != second {
			t.Error("relationship struct slice not set to correct value")
		}

		count, err := a.RefSeqDBUpepRefSeqEntries(tx).Count()
		if err != nil {
			t.Fatal(err)
		}
		if want := int64((i + 1) * 2); count != want {
			t.Error("want", want, "got", count)
		}
	}
}

func testUpepRefSeqDBToManySetOpRefSeqDBUpepRefSeqEntries(t *testing.T) {
	var err error

	tx := MustTx(boil.Begin())
	defer tx.Rollback()

	var a UpepRefSeqDB
	var b, c, d, e UpepRefSeqEntry

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, upepRefSeqDBDBTypes, false, strmangle.SetComplement(upepRefSeqDBPrimaryKeyColumns, upepRefSeqDBColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*UpepRefSeqEntry{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, upepRefSeqEntryDBTypes, false, strmangle.SetComplement(upepRefSeqEntryPrimaryKeyColumns, upepRefSeqEntryColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err = a.Insert(tx); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(tx); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(tx); err != nil {
		t.Fatal(err)
	}

	err = a.SetRefSeqDBUpepRefSeqEntries(tx, false, &b, &c)
	if err != nil {
		t.Fatal(err)
	}

	count, err := a.RefSeqDBUpepRefSeqEntries(tx).Count()
	if err != nil {
		t.Fatal(err)
	}
	if count != 2 {
		t.Error("count was wrong:", count)
	}

	err = a.SetRefSeqDBUpepRefSeqEntries(tx, true, &d, &e)
	if err != nil {
		t.Fatal(err)
	}

	count, err = a.RefSeqDBUpepRefSeqEntries(tx).Count()
	if err != nil {
		t.Fatal(err)
	}
	if count != 2 {
		t.Error("count was wrong:", count)
	}

	if b.RefSeqDBID.Valid {
		t.Error("want b's foreign key value to be nil")
	}
	if c.RefSeqDBID.Valid {
		t.Error("want c's foreign key value to be nil")
	}
	if a.ID != d.RefSeqDBID.Int64 {
		t.Error("foreign key was wrong value", a.ID, d.RefSeqDBID.Int64)
	}
	if a.ID != e.RefSeqDBID.Int64 {
		t.Error("foreign key was wrong value", a.ID, e.RefSeqDBID.Int64)
	}

	if b.R.RefSeqDB != nil {
		t.Error("relationship was not removed properly from the foreign struct")
	}
	if c.R.RefSeqDB != nil {
		t.Error("relationship was not removed properly from the foreign struct")
	}
	if d.R.RefSeqDB != &a {
		t.Error("relationship was not added properly to the foreign struct")
	}
	if e.R.RefSeqDB != &a {
		t.Error("relationship was not added properly to the foreign struct")
	}

	if a.R.RefSeqDBUpepRefSeqEntries[0] != &d {
		t.Error("relationship struct slice not set to correct value")
	}
	if a.R.RefSeqDBUpepRefSeqEntries[1] != &e {
		t.Error("relationship struct slice not set to correct value")
	}
}

func testUpepRefSeqDBToManyRemoveOpRefSeqDBUpepRefSeqEntries(t *testing.T) {
	var err error

	tx := MustTx(boil.Begin())
	defer tx.Rollback()

	var a UpepRefSeqDB
	var b, c, d, e UpepRefSeqEntry

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, upepRefSeqDBDBTypes, false, strmangle.SetComplement(upepRefSeqDBPrimaryKeyColumns, upepRefSeqDBColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*UpepRefSeqEntry{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, upepRefSeqEntryDBTypes, false, strmangle.SetComplement(upepRefSeqEntryPrimaryKeyColumns, upepRefSeqEntryColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err := a.Insert(tx); err != nil {
		t.Fatal(err)
	}

	err = a.AddRefSeqDBUpepRefSeqEntries(tx, true, foreigners...)
	if err != nil {
		t.Fatal(err)
	}

	count, err := a.RefSeqDBUpepRefSeqEntries(tx).Count()
	if err != nil {
		t.Fatal(err)
	}
	if count != 4 {
		t.Error("count was wrong:", count)
	}

	err = a.RemoveRefSeqDBUpepRefSeqEntries(tx, foreigners[:2]...)
	if err != nil {
		t.Fatal(err)
	}

	count, err = a.RefSeqDBUpepRefSeqEntries(tx).Count()
	if err != nil {
		t.Fatal(err)
	}
	if count != 2 {
		t.Error("count was wrong:", count)
	}

	if b.RefSeqDBID.Valid {
		t.Error("want b's foreign key value to be nil")
	}
	if c.RefSeqDBID.Valid {
		t.Error("want c's foreign key value to be nil")
	}

	if b.R.RefSeqDB != nil {
		t.Error("relationship was not removed properly from the foreign struct")
	}
	if c.R.RefSeqDB != nil {
		t.Error("relationship was not removed properly from the foreign struct")
	}
	if d.R.RefSeqDB != &a {
		t.Error("relationship to a should have been preserved")
	}
	if e.R.RefSeqDB != &a {
		t.Error("relationship to a should have been preserved")
	}

	if len(a.R.RefSeqDBUpepRefSeqEntries) != 2 {
		t.Error("should have preserved two relationships")
	}

	// Removal doesn't do a stable deletion for performance so we have to flip the order
	if a.R.RefSeqDBUpepRefSeqEntries[1] != &d {
		t.Error("relationship to d should have been preserved")
	}
	if a.R.RefSeqDBUpepRefSeqEntries[0] != &e {
		t.Error("relationship to e should have been preserved")
	}
}

func testUpepRefSeqDBSReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	upepRefSeqDB := &UpepRefSeqDB{}
	if err = randomize.Struct(seed, upepRefSeqDB, upepRefSeqDBDBTypes, true, upepRefSeqDBColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UpepRefSeqDB struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = upepRefSeqDB.Insert(tx); err != nil {
		t.Error(err)
	}

	if err = upepRefSeqDB.Reload(tx); err != nil {
		t.Error(err)
	}
}

func testUpepRefSeqDBSReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	upepRefSeqDB := &UpepRefSeqDB{}
	if err = randomize.Struct(seed, upepRefSeqDB, upepRefSeqDBDBTypes, true, upepRefSeqDBColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UpepRefSeqDB struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = upepRefSeqDB.Insert(tx); err != nil {
		t.Error(err)
	}

	slice := UpepRefSeqDBSlice{upepRefSeqDB}

	if err = slice.ReloadAll(tx); err != nil {
		t.Error(err)
	}
}
func testUpepRefSeqDBSSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	upepRefSeqDB := &UpepRefSeqDB{}
	if err = randomize.Struct(seed, upepRefSeqDB, upepRefSeqDBDBTypes, true, upepRefSeqDBColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UpepRefSeqDB struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = upepRefSeqDB.Insert(tx); err != nil {
		t.Error(err)
	}

	slice, err := UpepRefSeqDBS(tx).All()
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	upepRefSeqDBDBTypes = map[string]string{`CreatedAt`: `timestamp without time zone`, `ID`: `bigint`, `Name`: `text`, `UpdatedAt`: `timestamp without time zone`, `Version`: `integer`}
	_                   = bytes.MinRead
)

func testUpepRefSeqDBSUpdate(t *testing.T) {
	t.Parallel()

	if len(upepRefSeqDBColumns) == len(upepRefSeqDBPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	upepRefSeqDB := &UpepRefSeqDB{}
	if err = randomize.Struct(seed, upepRefSeqDB, upepRefSeqDBDBTypes, true, upepRefSeqDBColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UpepRefSeqDB struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = upepRefSeqDB.Insert(tx); err != nil {
		t.Error(err)
	}

	count, err := UpepRefSeqDBS(tx).Count()
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, upepRefSeqDB, upepRefSeqDBDBTypes, true, upepRefSeqDBColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UpepRefSeqDB struct: %s", err)
	}

	if err = upepRefSeqDB.Update(tx); err != nil {
		t.Error(err)
	}
}

func testUpepRefSeqDBSSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(upepRefSeqDBColumns) == len(upepRefSeqDBPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	upepRefSeqDB := &UpepRefSeqDB{}
	if err = randomize.Struct(seed, upepRefSeqDB, upepRefSeqDBDBTypes, true, upepRefSeqDBColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UpepRefSeqDB struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = upepRefSeqDB.Insert(tx); err != nil {
		t.Error(err)
	}

	count, err := UpepRefSeqDBS(tx).Count()
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, upepRefSeqDB, upepRefSeqDBDBTypes, true, upepRefSeqDBPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize UpepRefSeqDB struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(upepRefSeqDBColumns, upepRefSeqDBPrimaryKeyColumns) {
		fields = upepRefSeqDBColumns
	} else {
		fields = strmangle.SetComplement(
			upepRefSeqDBColumns,
			upepRefSeqDBPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(upepRefSeqDB))
	updateMap := M{}
	for _, col := range fields {
		updateMap[col] = value.FieldByName(strmangle.TitleCase(col)).Interface()
	}

	slice := UpepRefSeqDBSlice{upepRefSeqDB}
	if err = slice.UpdateAll(tx, updateMap); err != nil {
		t.Error(err)
	}
}
func testUpepRefSeqDBSUpsert(t *testing.T) {
	t.Parallel()

	if len(upepRefSeqDBColumns) == len(upepRefSeqDBPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	upepRefSeqDB := UpepRefSeqDB{}
	if err = randomize.Struct(seed, &upepRefSeqDB, upepRefSeqDBDBTypes, true); err != nil {
		t.Errorf("Unable to randomize UpepRefSeqDB struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = upepRefSeqDB.Upsert(tx, false, nil, nil); err != nil {
		t.Errorf("Unable to upsert UpepRefSeqDB: %s", err)
	}

	count, err := UpepRefSeqDBS(tx).Count()
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &upepRefSeqDB, upepRefSeqDBDBTypes, false, upepRefSeqDBPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize UpepRefSeqDB struct: %s", err)
	}

	if err = upepRefSeqDB.Upsert(tx, true, nil, nil); err != nil {
		t.Errorf("Unable to upsert UpepRefSeqDB: %s", err)
	}

	count, err = UpepRefSeqDBS(tx).Count()
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
