// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"database/sql"
	"fmt"
	"reflect"
	"strings"
	"sync"
	"time"

	"github.com/pkg/errors"
	"github.com/volatiletech/sqlboiler/boil"
	"github.com/volatiletech/sqlboiler/queries"
	"github.com/volatiletech/sqlboiler/queries/qm"
	"github.com/volatiletech/sqlboiler/strmangle"
	"gopkg.in/volatiletech/null.v6"
)

// UpepRefSeqDB is an object representing the database table.
type UpepRefSeqDB struct {
	ID        int64     `boil:"id" json:"id" toml:"id" yaml:"id"`
	CreatedAt null.Time `boil:"created_at" json:"created_at,omitempty" toml:"created_at" yaml:"created_at,omitempty"`
	UpdatedAt null.Time `boil:"updated_at" json:"updated_at,omitempty" toml:"updated_at" yaml:"updated_at,omitempty"`
	Name      string    `boil:"name" json:"name" toml:"name" yaml:"name"`
	Version   int       `boil:"version" json:"version" toml:"version" yaml:"version"`

	R *upepRefSeqDBR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L upepRefSeqDBL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var UpepRefSeqDBColumns = struct {
	ID        string
	CreatedAt string
	UpdatedAt string
	Name      string
	Version   string
}{
	ID:        "id",
	CreatedAt: "created_at",
	UpdatedAt: "updated_at",
	Name:      "name",
	Version:   "version",
}

// upepRefSeqDBR is where relationships are stored.
type upepRefSeqDBR struct {
	RefSeqDBUpepRefSeqEntries UpepRefSeqEntrySlice
}

// upepRefSeqDBL is where Load methods for each relationship are stored.
type upepRefSeqDBL struct{}

var (
	upepRefSeqDBColumns               = []string{"id", "created_at", "updated_at", "name", "version"}
	upepRefSeqDBColumnsWithoutDefault = []string{"created_at", "updated_at", "name"}
	upepRefSeqDBColumnsWithDefault    = []string{"id", "version"}
	upepRefSeqDBPrimaryKeyColumns     = []string{"id"}
)

type (
	// UpepRefSeqDBSlice is an alias for a slice of pointers to UpepRefSeqDB.
	// This should generally be used opposed to []UpepRefSeqDB.
	UpepRefSeqDBSlice []*UpepRefSeqDB
	// UpepRefSeqDBHook is the signature for custom UpepRefSeqDB hook methods
	UpepRefSeqDBHook func(boil.Executor, *UpepRefSeqDB) error

	upepRefSeqDBQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	upepRefSeqDBType                 = reflect.TypeOf(&UpepRefSeqDB{})
	upepRefSeqDBMapping              = queries.MakeStructMapping(upepRefSeqDBType)
	upepRefSeqDBPrimaryKeyMapping, _ = queries.BindMapping(upepRefSeqDBType, upepRefSeqDBMapping, upepRefSeqDBPrimaryKeyColumns)
	upepRefSeqDBInsertCacheMut       sync.RWMutex
	upepRefSeqDBInsertCache          = make(map[string]insertCache)
	upepRefSeqDBUpdateCacheMut       sync.RWMutex
	upepRefSeqDBUpdateCache          = make(map[string]updateCache)
	upepRefSeqDBUpsertCacheMut       sync.RWMutex
	upepRefSeqDBUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force bytes in case of primary key column that uses []byte (for relationship compares)
	_ = bytes.MinRead
)
var upepRefSeqDBBeforeInsertHooks []UpepRefSeqDBHook
var upepRefSeqDBBeforeUpdateHooks []UpepRefSeqDBHook
var upepRefSeqDBBeforeDeleteHooks []UpepRefSeqDBHook
var upepRefSeqDBBeforeUpsertHooks []UpepRefSeqDBHook

var upepRefSeqDBAfterInsertHooks []UpepRefSeqDBHook
var upepRefSeqDBAfterSelectHooks []UpepRefSeqDBHook
var upepRefSeqDBAfterUpdateHooks []UpepRefSeqDBHook
var upepRefSeqDBAfterDeleteHooks []UpepRefSeqDBHook
var upepRefSeqDBAfterUpsertHooks []UpepRefSeqDBHook

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *UpepRefSeqDB) doBeforeInsertHooks(exec boil.Executor) (err error) {
	for _, hook := range upepRefSeqDBBeforeInsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *UpepRefSeqDB) doBeforeUpdateHooks(exec boil.Executor) (err error) {
	for _, hook := range upepRefSeqDBBeforeUpdateHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *UpepRefSeqDB) doBeforeDeleteHooks(exec boil.Executor) (err error) {
	for _, hook := range upepRefSeqDBBeforeDeleteHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *UpepRefSeqDB) doBeforeUpsertHooks(exec boil.Executor) (err error) {
	for _, hook := range upepRefSeqDBBeforeUpsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *UpepRefSeqDB) doAfterInsertHooks(exec boil.Executor) (err error) {
	for _, hook := range upepRefSeqDBAfterInsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterSelectHooks executes all "after Select" hooks.
func (o *UpepRefSeqDB) doAfterSelectHooks(exec boil.Executor) (err error) {
	for _, hook := range upepRefSeqDBAfterSelectHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *UpepRefSeqDB) doAfterUpdateHooks(exec boil.Executor) (err error) {
	for _, hook := range upepRefSeqDBAfterUpdateHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *UpepRefSeqDB) doAfterDeleteHooks(exec boil.Executor) (err error) {
	for _, hook := range upepRefSeqDBAfterDeleteHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *UpepRefSeqDB) doAfterUpsertHooks(exec boil.Executor) (err error) {
	for _, hook := range upepRefSeqDBAfterUpsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddUpepRefSeqDBHook registers your hook function for all future operations.
func AddUpepRefSeqDBHook(hookPoint boil.HookPoint, upepRefSeqDBHook UpepRefSeqDBHook) {
	switch hookPoint {
	case boil.BeforeInsertHook:
		upepRefSeqDBBeforeInsertHooks = append(upepRefSeqDBBeforeInsertHooks, upepRefSeqDBHook)
	case boil.BeforeUpdateHook:
		upepRefSeqDBBeforeUpdateHooks = append(upepRefSeqDBBeforeUpdateHooks, upepRefSeqDBHook)
	case boil.BeforeDeleteHook:
		upepRefSeqDBBeforeDeleteHooks = append(upepRefSeqDBBeforeDeleteHooks, upepRefSeqDBHook)
	case boil.BeforeUpsertHook:
		upepRefSeqDBBeforeUpsertHooks = append(upepRefSeqDBBeforeUpsertHooks, upepRefSeqDBHook)
	case boil.AfterInsertHook:
		upepRefSeqDBAfterInsertHooks = append(upepRefSeqDBAfterInsertHooks, upepRefSeqDBHook)
	case boil.AfterSelectHook:
		upepRefSeqDBAfterSelectHooks = append(upepRefSeqDBAfterSelectHooks, upepRefSeqDBHook)
	case boil.AfterUpdateHook:
		upepRefSeqDBAfterUpdateHooks = append(upepRefSeqDBAfterUpdateHooks, upepRefSeqDBHook)
	case boil.AfterDeleteHook:
		upepRefSeqDBAfterDeleteHooks = append(upepRefSeqDBAfterDeleteHooks, upepRefSeqDBHook)
	case boil.AfterUpsertHook:
		upepRefSeqDBAfterUpsertHooks = append(upepRefSeqDBAfterUpsertHooks, upepRefSeqDBHook)
	}
}

// OneP returns a single upepRefSeqDB record from the query, and panics on error.
func (q upepRefSeqDBQuery) OneP() *UpepRefSeqDB {
	o, err := q.One()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return o
}

// One returns a single upepRefSeqDB record from the query.
func (q upepRefSeqDBQuery) One() (*UpepRefSeqDB, error) {
	o := &UpepRefSeqDB{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(o)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for upep_ref_seq_db")
	}

	if err := o.doAfterSelectHooks(queries.GetExecutor(q.Query)); err != nil {
		return o, err
	}

	return o, nil
}

// AllP returns all UpepRefSeqDB records from the query, and panics on error.
func (q upepRefSeqDBQuery) AllP() UpepRefSeqDBSlice {
	o, err := q.All()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return o
}

// All returns all UpepRefSeqDB records from the query.
func (q upepRefSeqDBQuery) All() (UpepRefSeqDBSlice, error) {
	var o []*UpepRefSeqDB

	err := q.Bind(&o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to UpepRefSeqDB slice")
	}

	if len(upepRefSeqDBAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(queries.GetExecutor(q.Query)); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// CountP returns the count of all UpepRefSeqDB records in the query, and panics on error.
func (q upepRefSeqDBQuery) CountP() int64 {
	c, err := q.Count()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return c
}

// Count returns the count of all UpepRefSeqDB records in the query.
func (q upepRefSeqDBQuery) Count() (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRow().Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count upep_ref_seq_db rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table, and panics on error.
func (q upepRefSeqDBQuery) ExistsP() bool {
	e, err := q.Exists()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}

// Exists checks if the row exists in the table.
func (q upepRefSeqDBQuery) Exists() (bool, error) {
	var count int64

	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRow().Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if upep_ref_seq_db exists")
	}

	return count > 0, nil
}

// RefSeqDBUpepRefSeqEntriesG retrieves all the upep_ref_seq_entry's upep ref seq entries via ref_seq_db_id column.
func (o *UpepRefSeqDB) RefSeqDBUpepRefSeqEntriesG(mods ...qm.QueryMod) upepRefSeqEntryQuery {
	return o.RefSeqDBUpepRefSeqEntries(boil.GetDB(), mods...)
}

// RefSeqDBUpepRefSeqEntries retrieves all the upep_ref_seq_entry's upep ref seq entries with an executor via ref_seq_db_id column.
func (o *UpepRefSeqDB) RefSeqDBUpepRefSeqEntries(exec boil.Executor, mods ...qm.QueryMod) upepRefSeqEntryQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"upep\".\"upep_ref_seq_entries\".\"ref_seq_db_id\"=?", o.ID),
	)

	query := UpepRefSeqEntries(exec, queryMods...)
	queries.SetFrom(query.Query, "\"upep\".\"upep_ref_seq_entries\"")

	if len(queries.GetSelect(query.Query)) == 0 {
		queries.SetSelect(query.Query, []string{"\"upep\".\"upep_ref_seq_entries\".*"})
	}

	return query
}

// LoadRefSeqDBUpepRefSeqEntries allows an eager lookup of values, cached into the
// loaded structs of the objects.
func (upepRefSeqDBL) LoadRefSeqDBUpepRefSeqEntries(e boil.Executor, singular bool, maybeUpepRefSeqDB interface{}) error {
	var slice []*UpepRefSeqDB
	var object *UpepRefSeqDB

	count := 1
	if singular {
		object = maybeUpepRefSeqDB.(*UpepRefSeqDB)
	} else {
		slice = *maybeUpepRefSeqDB.(*[]*UpepRefSeqDB)
		count = len(slice)
	}

	args := make([]interface{}, count)
	if singular {
		if object.R == nil {
			object.R = &upepRefSeqDBR{}
		}
		args[0] = object.ID
	} else {
		for i, obj := range slice {
			if obj.R == nil {
				obj.R = &upepRefSeqDBR{}
			}
			args[i] = obj.ID
		}
	}

	query := fmt.Sprintf(
		"select * from \"upep\".\"upep_ref_seq_entries\" where \"ref_seq_db_id\" in (%s)",
		strmangle.Placeholders(dialect.IndexPlaceholders, count, 1, 1),
	)
	if boil.DebugMode {
		fmt.Fprintf(boil.DebugWriter, "%s\n%v\n", query, args)
	}

	results, err := e.Query(query, args...)
	if err != nil {
		return errors.Wrap(err, "failed to eager load upep_ref_seq_entries")
	}
	defer results.Close()

	var resultSlice []*UpepRefSeqEntry
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice upep_ref_seq_entries")
	}

	if len(upepRefSeqEntryAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.RefSeqDBUpepRefSeqEntries = resultSlice
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.ID == foreign.RefSeqDBID.Int64 {
				local.R.RefSeqDBUpepRefSeqEntries = append(local.R.RefSeqDBUpepRefSeqEntries, foreign)
				break
			}
		}
	}

	return nil
}

// AddRefSeqDBUpepRefSeqEntriesG adds the given related objects to the existing relationships
// of the upep_ref_seq_db, optionally inserting them as new records.
// Appends related to o.R.RefSeqDBUpepRefSeqEntries.
// Sets related.R.RefSeqDB appropriately.
// Uses the global database handle.
func (o *UpepRefSeqDB) AddRefSeqDBUpepRefSeqEntriesG(insert bool, related ...*UpepRefSeqEntry) error {
	return o.AddRefSeqDBUpepRefSeqEntries(boil.GetDB(), insert, related...)
}

// AddRefSeqDBUpepRefSeqEntriesP adds the given related objects to the existing relationships
// of the upep_ref_seq_db, optionally inserting them as new records.
// Appends related to o.R.RefSeqDBUpepRefSeqEntries.
// Sets related.R.RefSeqDB appropriately.
// Panics on error.
func (o *UpepRefSeqDB) AddRefSeqDBUpepRefSeqEntriesP(exec boil.Executor, insert bool, related ...*UpepRefSeqEntry) {
	if err := o.AddRefSeqDBUpepRefSeqEntries(exec, insert, related...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// AddRefSeqDBUpepRefSeqEntriesGP adds the given related objects to the existing relationships
// of the upep_ref_seq_db, optionally inserting them as new records.
// Appends related to o.R.RefSeqDBUpepRefSeqEntries.
// Sets related.R.RefSeqDB appropriately.
// Uses the global database handle and panics on error.
func (o *UpepRefSeqDB) AddRefSeqDBUpepRefSeqEntriesGP(insert bool, related ...*UpepRefSeqEntry) {
	if err := o.AddRefSeqDBUpepRefSeqEntries(boil.GetDB(), insert, related...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// AddRefSeqDBUpepRefSeqEntries adds the given related objects to the existing relationships
// of the upep_ref_seq_db, optionally inserting them as new records.
// Appends related to o.R.RefSeqDBUpepRefSeqEntries.
// Sets related.R.RefSeqDB appropriately.
func (o *UpepRefSeqDB) AddRefSeqDBUpepRefSeqEntries(exec boil.Executor, insert bool, related ...*UpepRefSeqEntry) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.RefSeqDBID.Int64 = o.ID
			rel.RefSeqDBID.Valid = true
			if err = rel.Insert(exec); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"upep\".\"upep_ref_seq_entries\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"ref_seq_db_id"}),
				strmangle.WhereClause("\"", "\"", 2, upepRefSeqEntryPrimaryKeyColumns),
			)
			values := []interface{}{o.ID, rel.ID}

			if boil.DebugMode {
				fmt.Fprintln(boil.DebugWriter, updateQuery)
				fmt.Fprintln(boil.DebugWriter, values)
			}

			if _, err = exec.Exec(updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.RefSeqDBID.Int64 = o.ID
			rel.RefSeqDBID.Valid = true
		}
	}

	if o.R == nil {
		o.R = &upepRefSeqDBR{
			RefSeqDBUpepRefSeqEntries: related,
		}
	} else {
		o.R.RefSeqDBUpepRefSeqEntries = append(o.R.RefSeqDBUpepRefSeqEntries, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &upepRefSeqEntryR{
				RefSeqDB: o,
			}
		} else {
			rel.R.RefSeqDB = o
		}
	}
	return nil
}

// SetRefSeqDBUpepRefSeqEntriesG removes all previously related items of the
// upep_ref_seq_db replacing them completely with the passed
// in related items, optionally inserting them as new records.
// Sets o.R.RefSeqDB's RefSeqDBUpepRefSeqEntries accordingly.
// Replaces o.R.RefSeqDBUpepRefSeqEntries with related.
// Sets related.R.RefSeqDB's RefSeqDBUpepRefSeqEntries accordingly.
// Uses the global database handle.
func (o *UpepRefSeqDB) SetRefSeqDBUpepRefSeqEntriesG(insert bool, related ...*UpepRefSeqEntry) error {
	return o.SetRefSeqDBUpepRefSeqEntries(boil.GetDB(), insert, related...)
}

// SetRefSeqDBUpepRefSeqEntriesP removes all previously related items of the
// upep_ref_seq_db replacing them completely with the passed
// in related items, optionally inserting them as new records.
// Sets o.R.RefSeqDB's RefSeqDBUpepRefSeqEntries accordingly.
// Replaces o.R.RefSeqDBUpepRefSeqEntries with related.
// Sets related.R.RefSeqDB's RefSeqDBUpepRefSeqEntries accordingly.
// Panics on error.
func (o *UpepRefSeqDB) SetRefSeqDBUpepRefSeqEntriesP(exec boil.Executor, insert bool, related ...*UpepRefSeqEntry) {
	if err := o.SetRefSeqDBUpepRefSeqEntries(exec, insert, related...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// SetRefSeqDBUpepRefSeqEntriesGP removes all previously related items of the
// upep_ref_seq_db replacing them completely with the passed
// in related items, optionally inserting them as new records.
// Sets o.R.RefSeqDB's RefSeqDBUpepRefSeqEntries accordingly.
// Replaces o.R.RefSeqDBUpepRefSeqEntries with related.
// Sets related.R.RefSeqDB's RefSeqDBUpepRefSeqEntries accordingly.
// Uses the global database handle and panics on error.
func (o *UpepRefSeqDB) SetRefSeqDBUpepRefSeqEntriesGP(insert bool, related ...*UpepRefSeqEntry) {
	if err := o.SetRefSeqDBUpepRefSeqEntries(boil.GetDB(), insert, related...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// SetRefSeqDBUpepRefSeqEntries removes all previously related items of the
// upep_ref_seq_db replacing them completely with the passed
// in related items, optionally inserting them as new records.
// Sets o.R.RefSeqDB's RefSeqDBUpepRefSeqEntries accordingly.
// Replaces o.R.RefSeqDBUpepRefSeqEntries with related.
// Sets related.R.RefSeqDB's RefSeqDBUpepRefSeqEntries accordingly.
func (o *UpepRefSeqDB) SetRefSeqDBUpepRefSeqEntries(exec boil.Executor, insert bool, related ...*UpepRefSeqEntry) error {
	query := "update \"upep\".\"upep_ref_seq_entries\" set \"ref_seq_db_id\" = null where \"ref_seq_db_id\" = $1"
	values := []interface{}{o.ID}
	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, query)
		fmt.Fprintln(boil.DebugWriter, values)
	}

	_, err := exec.Exec(query, values...)
	if err != nil {
		return errors.Wrap(err, "failed to remove relationships before set")
	}

	if o.R != nil {
		for _, rel := range o.R.RefSeqDBUpepRefSeqEntries {
			rel.RefSeqDBID.Valid = false
			if rel.R == nil {
				continue
			}

			rel.R.RefSeqDB = nil
		}

		o.R.RefSeqDBUpepRefSeqEntries = nil
	}
	return o.AddRefSeqDBUpepRefSeqEntries(exec, insert, related...)
}

// RemoveRefSeqDBUpepRefSeqEntriesG relationships from objects passed in.
// Removes related items from R.RefSeqDBUpepRefSeqEntries (uses pointer comparison, removal does not keep order)
// Sets related.R.RefSeqDB.
// Uses the global database handle.
func (o *UpepRefSeqDB) RemoveRefSeqDBUpepRefSeqEntriesG(related ...*UpepRefSeqEntry) error {
	return o.RemoveRefSeqDBUpepRefSeqEntries(boil.GetDB(), related...)
}

// RemoveRefSeqDBUpepRefSeqEntriesP relationships from objects passed in.
// Removes related items from R.RefSeqDBUpepRefSeqEntries (uses pointer comparison, removal does not keep order)
// Sets related.R.RefSeqDB.
// Panics on error.
func (o *UpepRefSeqDB) RemoveRefSeqDBUpepRefSeqEntriesP(exec boil.Executor, related ...*UpepRefSeqEntry) {
	if err := o.RemoveRefSeqDBUpepRefSeqEntries(exec, related...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// RemoveRefSeqDBUpepRefSeqEntriesGP relationships from objects passed in.
// Removes related items from R.RefSeqDBUpepRefSeqEntries (uses pointer comparison, removal does not keep order)
// Sets related.R.RefSeqDB.
// Uses the global database handle and panics on error.
func (o *UpepRefSeqDB) RemoveRefSeqDBUpepRefSeqEntriesGP(related ...*UpepRefSeqEntry) {
	if err := o.RemoveRefSeqDBUpepRefSeqEntries(boil.GetDB(), related...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// RemoveRefSeqDBUpepRefSeqEntries relationships from objects passed in.
// Removes related items from R.RefSeqDBUpepRefSeqEntries (uses pointer comparison, removal does not keep order)
// Sets related.R.RefSeqDB.
func (o *UpepRefSeqDB) RemoveRefSeqDBUpepRefSeqEntries(exec boil.Executor, related ...*UpepRefSeqEntry) error {
	var err error
	for _, rel := range related {
		rel.RefSeqDBID.Valid = false
		if rel.R != nil {
			rel.R.RefSeqDB = nil
		}
		if err = rel.Update(exec, "ref_seq_db_id"); err != nil {
			return err
		}
	}
	if o.R == nil {
		return nil
	}

	for _, rel := range related {
		for i, ri := range o.R.RefSeqDBUpepRefSeqEntries {
			if rel != ri {
				continue
			}

			ln := len(o.R.RefSeqDBUpepRefSeqEntries)
			if ln > 1 && i < ln-1 {
				o.R.RefSeqDBUpepRefSeqEntries[i] = o.R.RefSeqDBUpepRefSeqEntries[ln-1]
			}
			o.R.RefSeqDBUpepRefSeqEntries = o.R.RefSeqDBUpepRefSeqEntries[:ln-1]
			break
		}
	}

	return nil
}

// UpepRefSeqDBSG retrieves all records.
func UpepRefSeqDBSG(mods ...qm.QueryMod) upepRefSeqDBQuery {
	return UpepRefSeqDBS(boil.GetDB(), mods...)
}

// UpepRefSeqDBS retrieves all the records using an executor.
func UpepRefSeqDBS(exec boil.Executor, mods ...qm.QueryMod) upepRefSeqDBQuery {
	mods = append(mods, qm.From("\"upep\".\"upep_ref_seq_db\""))
	return upepRefSeqDBQuery{NewQuery(exec, mods...)}
}

// FindUpepRefSeqDBG retrieves a single record by ID.
func FindUpepRefSeqDBG(id int64, selectCols ...string) (*UpepRefSeqDB, error) {
	return FindUpepRefSeqDB(boil.GetDB(), id, selectCols...)
}

// FindUpepRefSeqDBGP retrieves a single record by ID, and panics on error.
func FindUpepRefSeqDBGP(id int64, selectCols ...string) *UpepRefSeqDB {
	retobj, err := FindUpepRefSeqDB(boil.GetDB(), id, selectCols...)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return retobj
}

// FindUpepRefSeqDB retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindUpepRefSeqDB(exec boil.Executor, id int64, selectCols ...string) (*UpepRefSeqDB, error) {
	upepRefSeqDBObj := &UpepRefSeqDB{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"upep\".\"upep_ref_seq_db\" where \"id\"=$1", sel,
	)

	q := queries.Raw(exec, query, id)

	err := q.Bind(upepRefSeqDBObj)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from upep_ref_seq_db")
	}

	return upepRefSeqDBObj, nil
}

// FindUpepRefSeqDBP retrieves a single record by ID with an executor, and panics on error.
func FindUpepRefSeqDBP(exec boil.Executor, id int64, selectCols ...string) *UpepRefSeqDB {
	retobj, err := FindUpepRefSeqDB(exec, id, selectCols...)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return retobj
}

// InsertG a single record. See Insert for whitelist behavior description.
func (o *UpepRefSeqDB) InsertG(whitelist ...string) error {
	return o.Insert(boil.GetDB(), whitelist...)
}

// InsertGP a single record, and panics on error. See Insert for whitelist
// behavior description.
func (o *UpepRefSeqDB) InsertGP(whitelist ...string) {
	if err := o.Insert(boil.GetDB(), whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// InsertP a single record using an executor, and panics on error. See Insert
// for whitelist behavior description.
func (o *UpepRefSeqDB) InsertP(exec boil.Executor, whitelist ...string) {
	if err := o.Insert(exec, whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Insert a single record using an executor.
// Whitelist behavior: If a whitelist is provided, only those columns supplied are inserted
// No whitelist behavior: Without a whitelist, columns are inferred by the following rules:
// - All columns without a default value are included (i.e. name, age)
// - All columns with a default, but non-zero are included (i.e. health = 75)
func (o *UpepRefSeqDB) Insert(exec boil.Executor, whitelist ...string) error {
	if o == nil {
		return errors.New("models: no upep_ref_seq_db provided for insertion")
	}

	var err error
	currTime := time.Now().In(boil.GetLocation())

	if o.CreatedAt.Time.IsZero() {
		o.CreatedAt.Time = currTime
		o.CreatedAt.Valid = true
	}
	if o.UpdatedAt.Time.IsZero() {
		o.UpdatedAt.Time = currTime
		o.UpdatedAt.Valid = true
	}

	if err := o.doBeforeInsertHooks(exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(upepRefSeqDBColumnsWithDefault, o)

	key := makeCacheKey(whitelist, nzDefaults)
	upepRefSeqDBInsertCacheMut.RLock()
	cache, cached := upepRefSeqDBInsertCache[key]
	upepRefSeqDBInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := strmangle.InsertColumnSet(
			upepRefSeqDBColumns,
			upepRefSeqDBColumnsWithDefault,
			upepRefSeqDBColumnsWithoutDefault,
			nzDefaults,
			whitelist,
		)

		cache.valueMapping, err = queries.BindMapping(upepRefSeqDBType, upepRefSeqDBMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(upepRefSeqDBType, upepRefSeqDBMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"upep\".\"upep_ref_seq_db\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.IndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"upep\".\"upep_ref_seq_db\" DEFAULT VALUES"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		if len(wl) != 0 {
			cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRow(cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.Exec(cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into upep_ref_seq_db")
	}

	if !cached {
		upepRefSeqDBInsertCacheMut.Lock()
		upepRefSeqDBInsertCache[key] = cache
		upepRefSeqDBInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(exec)
}

// UpdateG a single UpepRefSeqDB record. See Update for
// whitelist behavior description.
func (o *UpepRefSeqDB) UpdateG(whitelist ...string) error {
	return o.Update(boil.GetDB(), whitelist...)
}

// UpdateGP a single UpepRefSeqDB record.
// UpdateGP takes a whitelist of column names that should be updated.
// Panics on error. See Update for whitelist behavior description.
func (o *UpepRefSeqDB) UpdateGP(whitelist ...string) {
	if err := o.Update(boil.GetDB(), whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateP uses an executor to update the UpepRefSeqDB, and panics on error.
// See Update for whitelist behavior description.
func (o *UpepRefSeqDB) UpdateP(exec boil.Executor, whitelist ...string) {
	err := o.Update(exec, whitelist...)
	if err != nil {
		panic(boil.WrapErr(err))
	}
}

// Update uses an executor to update the UpepRefSeqDB.
// Whitelist behavior: If a whitelist is provided, only the columns given are updated.
// No whitelist behavior: Without a whitelist, columns are inferred by the following rules:
// - All columns are inferred to start with
// - All primary keys are subtracted from this set
// Update does not automatically update the record in case of default values. Use .Reload()
// to refresh the records.
func (o *UpepRefSeqDB) Update(exec boil.Executor, whitelist ...string) error {
	currTime := time.Now().In(boil.GetLocation())

	o.UpdatedAt.Time = currTime
	o.UpdatedAt.Valid = true

	var err error
	if err = o.doBeforeUpdateHooks(exec); err != nil {
		return err
	}
	key := makeCacheKey(whitelist, nil)
	upepRefSeqDBUpdateCacheMut.RLock()
	cache, cached := upepRefSeqDBUpdateCache[key]
	upepRefSeqDBUpdateCacheMut.RUnlock()

	if !cached {
		wl := strmangle.UpdateColumnSet(
			upepRefSeqDBColumns,
			upepRefSeqDBPrimaryKeyColumns,
			whitelist,
		)

		if len(whitelist) == 0 {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return errors.New("models: unable to update upep_ref_seq_db, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"upep\".\"upep_ref_seq_db\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, upepRefSeqDBPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(upepRefSeqDBType, upepRefSeqDBMapping, append(wl, upepRefSeqDBPrimaryKeyColumns...))
		if err != nil {
			return err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, values)
	}

	_, err = exec.Exec(cache.query, values...)
	if err != nil {
		return errors.Wrap(err, "models: unable to update upep_ref_seq_db row")
	}

	if !cached {
		upepRefSeqDBUpdateCacheMut.Lock()
		upepRefSeqDBUpdateCache[key] = cache
		upepRefSeqDBUpdateCacheMut.Unlock()
	}

	return o.doAfterUpdateHooks(exec)
}

// UpdateAllP updates all rows with matching column names, and panics on error.
func (q upepRefSeqDBQuery) UpdateAllP(cols M) {
	if err := q.UpdateAll(cols); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateAll updates all rows with the specified column values.
func (q upepRefSeqDBQuery) UpdateAll(cols M) error {
	queries.SetUpdate(q.Query, cols)

	_, err := q.Query.Exec()
	if err != nil {
		return errors.Wrap(err, "models: unable to update all for upep_ref_seq_db")
	}

	return nil
}

// UpdateAllG updates all rows with the specified column values.
func (o UpepRefSeqDBSlice) UpdateAllG(cols M) error {
	return o.UpdateAll(boil.GetDB(), cols)
}

// UpdateAllGP updates all rows with the specified column values, and panics on error.
func (o UpepRefSeqDBSlice) UpdateAllGP(cols M) {
	if err := o.UpdateAll(boil.GetDB(), cols); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateAllP updates all rows with the specified column values, and panics on error.
func (o UpepRefSeqDBSlice) UpdateAllP(exec boil.Executor, cols M) {
	if err := o.UpdateAll(exec, cols); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o UpepRefSeqDBSlice) UpdateAll(exec boil.Executor, cols M) error {
	ln := int64(len(o))
	if ln == 0 {
		return nil
	}

	if len(cols) == 0 {
		return errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), upepRefSeqDBPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"upep\".\"upep_ref_seq_db\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, upepRefSeqDBPrimaryKeyColumns, len(o)))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}

	_, err := exec.Exec(sql, args...)
	if err != nil {
		return errors.Wrap(err, "models: unable to update all in upepRefSeqDB slice")
	}

	return nil
}

// UpsertG attempts an insert, and does an update or ignore on conflict.
func (o *UpepRefSeqDB) UpsertG(updateOnConflict bool, conflictColumns []string, updateColumns []string, whitelist ...string) error {
	return o.Upsert(boil.GetDB(), updateOnConflict, conflictColumns, updateColumns, whitelist...)
}

// UpsertGP attempts an insert, and does an update or ignore on conflict. Panics on error.
func (o *UpepRefSeqDB) UpsertGP(updateOnConflict bool, conflictColumns []string, updateColumns []string, whitelist ...string) {
	if err := o.Upsert(boil.GetDB(), updateOnConflict, conflictColumns, updateColumns, whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpsertP attempts an insert using an executor, and does an update or ignore on conflict.
// UpsertP panics on error.
func (o *UpepRefSeqDB) UpsertP(exec boil.Executor, updateOnConflict bool, conflictColumns []string, updateColumns []string, whitelist ...string) {
	if err := o.Upsert(exec, updateOnConflict, conflictColumns, updateColumns, whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
func (o *UpepRefSeqDB) Upsert(exec boil.Executor, updateOnConflict bool, conflictColumns []string, updateColumns []string, whitelist ...string) error {
	if o == nil {
		return errors.New("models: no upep_ref_seq_db provided for upsert")
	}
	currTime := time.Now().In(boil.GetLocation())

	if o.CreatedAt.Time.IsZero() {
		o.CreatedAt.Time = currTime
		o.CreatedAt.Valid = true
	}
	o.UpdatedAt.Time = currTime
	o.UpdatedAt.Valid = true

	if err := o.doBeforeUpsertHooks(exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(upepRefSeqDBColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs postgres problems
	buf := strmangle.GetBuffer()

	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range updateColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range whitelist {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	upepRefSeqDBUpsertCacheMut.RLock()
	cache, cached := upepRefSeqDBUpsertCache[key]
	upepRefSeqDBUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := strmangle.InsertColumnSet(
			upepRefSeqDBColumns,
			upepRefSeqDBColumnsWithDefault,
			upepRefSeqDBColumnsWithoutDefault,
			nzDefaults,
			whitelist,
		)

		update := strmangle.UpdateColumnSet(
			upepRefSeqDBColumns,
			upepRefSeqDBPrimaryKeyColumns,
			updateColumns,
		)
		if len(update) == 0 {
			return errors.New("models: unable to upsert upep_ref_seq_db, could not build update column list")
		}

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(upepRefSeqDBPrimaryKeyColumns))
			copy(conflict, upepRefSeqDBPrimaryKeyColumns)
		}
		cache.query = queries.BuildUpsertQueryPostgres(dialect, "\"upep\".\"upep_ref_seq_db\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(upepRefSeqDBType, upepRefSeqDBMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(upepRefSeqDBType, upepRefSeqDBMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRow(cache.query, vals...).Scan(returns...)
		if err == sql.ErrNoRows {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.Exec(cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert upep_ref_seq_db")
	}

	if !cached {
		upepRefSeqDBUpsertCacheMut.Lock()
		upepRefSeqDBUpsertCache[key] = cache
		upepRefSeqDBUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(exec)
}

// DeleteP deletes a single UpepRefSeqDB record with an executor.
// DeleteP will match against the primary key column to find the record to delete.
// Panics on error.
func (o *UpepRefSeqDB) DeleteP(exec boil.Executor) {
	if err := o.Delete(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteG deletes a single UpepRefSeqDB record.
// DeleteG will match against the primary key column to find the record to delete.
func (o *UpepRefSeqDB) DeleteG() error {
	if o == nil {
		return errors.New("models: no UpepRefSeqDB provided for deletion")
	}

	return o.Delete(boil.GetDB())
}

// DeleteGP deletes a single UpepRefSeqDB record.
// DeleteGP will match against the primary key column to find the record to delete.
// Panics on error.
func (o *UpepRefSeqDB) DeleteGP() {
	if err := o.DeleteG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Delete deletes a single UpepRefSeqDB record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *UpepRefSeqDB) Delete(exec boil.Executor) error {
	if o == nil {
		return errors.New("models: no UpepRefSeqDB provided for delete")
	}

	if err := o.doBeforeDeleteHooks(exec); err != nil {
		return err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), upepRefSeqDBPrimaryKeyMapping)
	sql := "DELETE FROM \"upep\".\"upep_ref_seq_db\" WHERE \"id\"=$1"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}

	_, err := exec.Exec(sql, args...)
	if err != nil {
		return errors.Wrap(err, "models: unable to delete from upep_ref_seq_db")
	}

	if err := o.doAfterDeleteHooks(exec); err != nil {
		return err
	}

	return nil
}

// DeleteAllP deletes all rows, and panics on error.
func (q upepRefSeqDBQuery) DeleteAllP() {
	if err := q.DeleteAll(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteAll deletes all matching rows.
func (q upepRefSeqDBQuery) DeleteAll() error {
	if q.Query == nil {
		return errors.New("models: no upepRefSeqDBQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	_, err := q.Query.Exec()
	if err != nil {
		return errors.Wrap(err, "models: unable to delete all from upep_ref_seq_db")
	}

	return nil
}

// DeleteAllGP deletes all rows in the slice, and panics on error.
func (o UpepRefSeqDBSlice) DeleteAllGP() {
	if err := o.DeleteAllG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteAllG deletes all rows in the slice.
func (o UpepRefSeqDBSlice) DeleteAllG() error {
	if o == nil {
		return errors.New("models: no UpepRefSeqDB slice provided for delete all")
	}
	return o.DeleteAll(boil.GetDB())
}

// DeleteAllP deletes all rows in the slice, using an executor, and panics on error.
func (o UpepRefSeqDBSlice) DeleteAllP(exec boil.Executor) {
	if err := o.DeleteAll(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o UpepRefSeqDBSlice) DeleteAll(exec boil.Executor) error {
	if o == nil {
		return errors.New("models: no UpepRefSeqDB slice provided for delete all")
	}

	if len(o) == 0 {
		return nil
	}

	if len(upepRefSeqDBBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(exec); err != nil {
				return err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), upepRefSeqDBPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"upep\".\"upep_ref_seq_db\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, upepRefSeqDBPrimaryKeyColumns, len(o))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args)
	}

	_, err := exec.Exec(sql, args...)
	if err != nil {
		return errors.Wrap(err, "models: unable to delete all from upepRefSeqDB slice")
	}

	if len(upepRefSeqDBAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(exec); err != nil {
				return err
			}
		}
	}

	return nil
}

// ReloadGP refetches the object from the database and panics on error.
func (o *UpepRefSeqDB) ReloadGP() {
	if err := o.ReloadG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadP refetches the object from the database with an executor. Panics on error.
func (o *UpepRefSeqDB) ReloadP(exec boil.Executor) {
	if err := o.Reload(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadG refetches the object from the database using the primary keys.
func (o *UpepRefSeqDB) ReloadG() error {
	if o == nil {
		return errors.New("models: no UpepRefSeqDB provided for reload")
	}

	return o.Reload(boil.GetDB())
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *UpepRefSeqDB) Reload(exec boil.Executor) error {
	ret, err := FindUpepRefSeqDB(exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAllGP refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
// Panics on error.
func (o *UpepRefSeqDBSlice) ReloadAllGP() {
	if err := o.ReloadAllG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadAllP refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
// Panics on error.
func (o *UpepRefSeqDBSlice) ReloadAllP(exec boil.Executor) {
	if err := o.ReloadAll(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadAllG refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *UpepRefSeqDBSlice) ReloadAllG() error {
	if o == nil {
		return errors.New("models: empty UpepRefSeqDBSlice provided for reload all")
	}

	return o.ReloadAll(boil.GetDB())
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *UpepRefSeqDBSlice) ReloadAll(exec boil.Executor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	upepRefSeqDBS := UpepRefSeqDBSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), upepRefSeqDBPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"upep\".\"upep_ref_seq_db\".* FROM \"upep\".\"upep_ref_seq_db\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, upepRefSeqDBPrimaryKeyColumns, len(*o))

	q := queries.Raw(exec, sql, args...)

	err := q.Bind(&upepRefSeqDBS)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in UpepRefSeqDBSlice")
	}

	*o = upepRefSeqDBS

	return nil
}

// UpepRefSeqDBExists checks if the UpepRefSeqDB row exists.
func UpepRefSeqDBExists(exec boil.Executor, id int64) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"upep\".\"upep_ref_seq_db\" where \"id\"=$1 limit 1)"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, id)
	}

	row := exec.QueryRow(sql, id)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if upep_ref_seq_db exists")
	}

	return exists, nil
}

// UpepRefSeqDBExistsG checks if the UpepRefSeqDB row exists.
func UpepRefSeqDBExistsG(id int64) (bool, error) {
	return UpepRefSeqDBExists(boil.GetDB(), id)
}

// UpepRefSeqDBExistsGP checks if the UpepRefSeqDB row exists. Panics on error.
func UpepRefSeqDBExistsGP(id int64) bool {
	e, err := UpepRefSeqDBExists(boil.GetDB(), id)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}

// UpepRefSeqDBExistsP checks if the UpepRefSeqDB row exists. Panics on error.
func UpepRefSeqDBExistsP(exec boil.Executor, id int64) bool {
	e, err := UpepRefSeqDBExists(exec, id)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}
