// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"database/sql"
	"fmt"
	"reflect"
	"strings"
	"sync"
	"time"

	"github.com/pkg/errors"
	"github.com/volatiletech/sqlboiler/boil"
	"github.com/volatiletech/sqlboiler/queries"
	"github.com/volatiletech/sqlboiler/queries/qm"
	"github.com/volatiletech/sqlboiler/strmangle"
	"gopkg.in/volatiletech/null.v6"
)

// UpepSorfPo is an object representing the database table.
type UpepSorfPo struct {
	ID               int64     `boil:"id" json:"id" toml:"id" yaml:"id"`
	CreatedAt        null.Time `boil:"created_at" json:"created_at,omitempty" toml:"created_at" yaml:"created_at,omitempty"`
	UpdatedAt        null.Time `boil:"updated_at" json:"updated_at,omitempty" toml:"updated_at" yaml:"updated_at,omitempty"`
	StartingPosition int       `boil:"starting_position" json:"starting_position" toml:"starting_position" yaml:"starting_position"`
	EndingPosition   int       `boil:"ending_position" json:"ending_position" toml:"ending_position" yaml:"ending_position"`
	RefSeqEntryID    int64     `boil:"ref_seq_entry_id" json:"ref_seq_entry_id" toml:"ref_seq_entry_id" yaml:"ref_seq_entry_id"`
	StartingCodonID  int64     `boil:"starting_codon_id" json:"starting_codon_id" toml:"starting_codon_id" yaml:"starting_codon_id"`
	EndingCodonID    int64     `boil:"ending_codon_id" json:"ending_codon_id" toml:"ending_codon_id" yaml:"ending_codon_id"`

	R *upepSorfPoR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L upepSorfPoL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var UpepSorfPoColumns = struct {
	ID               string
	CreatedAt        string
	UpdatedAt        string
	StartingPosition string
	EndingPosition   string
	RefSeqEntryID    string
	StartingCodonID  string
	EndingCodonID    string
}{
	ID:               "id",
	CreatedAt:        "created_at",
	UpdatedAt:        "updated_at",
	StartingPosition: "starting_position",
	EndingPosition:   "ending_position",
	RefSeqEntryID:    "ref_seq_entry_id",
	StartingCodonID:  "starting_codon_id",
	EndingCodonID:    "ending_codon_id",
}

// upepSorfPoR is where relationships are stored.
type upepSorfPoR struct {
	RefSeqEntry   *UpepRefSeqEntry
	StartingCodon *UpepCodon
	EndingCodon   *UpepCodon
}

// upepSorfPoL is where Load methods for each relationship are stored.
type upepSorfPoL struct{}

var (
	upepSorfPoColumns               = []string{"id", "created_at", "updated_at", "starting_position", "ending_position", "ref_seq_entry_id", "starting_codon_id", "ending_codon_id"}
	upepSorfPoColumnsWithoutDefault = []string{"id", "created_at", "updated_at", "starting_position", "ending_position", "ref_seq_entry_id", "starting_codon_id", "ending_codon_id"}
	upepSorfPoColumnsWithDefault    = []string{}
	upepSorfPoPrimaryKeyColumns     = []string{"id"}
)

type (
	// UpepSorfPoSlice is an alias for a slice of pointers to UpepSorfPo.
	// This should generally be used opposed to []UpepSorfPo.
	UpepSorfPoSlice []*UpepSorfPo
	// UpepSorfPoHook is the signature for custom UpepSorfPo hook methods
	UpepSorfPoHook func(boil.Executor, *UpepSorfPo) error

	upepSorfPoQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	upepSorfPoType                 = reflect.TypeOf(&UpepSorfPo{})
	upepSorfPoMapping              = queries.MakeStructMapping(upepSorfPoType)
	upepSorfPoPrimaryKeyMapping, _ = queries.BindMapping(upepSorfPoType, upepSorfPoMapping, upepSorfPoPrimaryKeyColumns)
	upepSorfPoInsertCacheMut       sync.RWMutex
	upepSorfPoInsertCache          = make(map[string]insertCache)
	upepSorfPoUpdateCacheMut       sync.RWMutex
	upepSorfPoUpdateCache          = make(map[string]updateCache)
	upepSorfPoUpsertCacheMut       sync.RWMutex
	upepSorfPoUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force bytes in case of primary key column that uses []byte (for relationship compares)
	_ = bytes.MinRead
)
var upepSorfPoBeforeInsertHooks []UpepSorfPoHook
var upepSorfPoBeforeUpdateHooks []UpepSorfPoHook
var upepSorfPoBeforeDeleteHooks []UpepSorfPoHook
var upepSorfPoBeforeUpsertHooks []UpepSorfPoHook

var upepSorfPoAfterInsertHooks []UpepSorfPoHook
var upepSorfPoAfterSelectHooks []UpepSorfPoHook
var upepSorfPoAfterUpdateHooks []UpepSorfPoHook
var upepSorfPoAfterDeleteHooks []UpepSorfPoHook
var upepSorfPoAfterUpsertHooks []UpepSorfPoHook

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *UpepSorfPo) doBeforeInsertHooks(exec boil.Executor) (err error) {
	for _, hook := range upepSorfPoBeforeInsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *UpepSorfPo) doBeforeUpdateHooks(exec boil.Executor) (err error) {
	for _, hook := range upepSorfPoBeforeUpdateHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *UpepSorfPo) doBeforeDeleteHooks(exec boil.Executor) (err error) {
	for _, hook := range upepSorfPoBeforeDeleteHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *UpepSorfPo) doBeforeUpsertHooks(exec boil.Executor) (err error) {
	for _, hook := range upepSorfPoBeforeUpsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *UpepSorfPo) doAfterInsertHooks(exec boil.Executor) (err error) {
	for _, hook := range upepSorfPoAfterInsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterSelectHooks executes all "after Select" hooks.
func (o *UpepSorfPo) doAfterSelectHooks(exec boil.Executor) (err error) {
	for _, hook := range upepSorfPoAfterSelectHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *UpepSorfPo) doAfterUpdateHooks(exec boil.Executor) (err error) {
	for _, hook := range upepSorfPoAfterUpdateHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *UpepSorfPo) doAfterDeleteHooks(exec boil.Executor) (err error) {
	for _, hook := range upepSorfPoAfterDeleteHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *UpepSorfPo) doAfterUpsertHooks(exec boil.Executor) (err error) {
	for _, hook := range upepSorfPoAfterUpsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddUpepSorfPoHook registers your hook function for all future operations.
func AddUpepSorfPoHook(hookPoint boil.HookPoint, upepSorfPoHook UpepSorfPoHook) {
	switch hookPoint {
	case boil.BeforeInsertHook:
		upepSorfPoBeforeInsertHooks = append(upepSorfPoBeforeInsertHooks, upepSorfPoHook)
	case boil.BeforeUpdateHook:
		upepSorfPoBeforeUpdateHooks = append(upepSorfPoBeforeUpdateHooks, upepSorfPoHook)
	case boil.BeforeDeleteHook:
		upepSorfPoBeforeDeleteHooks = append(upepSorfPoBeforeDeleteHooks, upepSorfPoHook)
	case boil.BeforeUpsertHook:
		upepSorfPoBeforeUpsertHooks = append(upepSorfPoBeforeUpsertHooks, upepSorfPoHook)
	case boil.AfterInsertHook:
		upepSorfPoAfterInsertHooks = append(upepSorfPoAfterInsertHooks, upepSorfPoHook)
	case boil.AfterSelectHook:
		upepSorfPoAfterSelectHooks = append(upepSorfPoAfterSelectHooks, upepSorfPoHook)
	case boil.AfterUpdateHook:
		upepSorfPoAfterUpdateHooks = append(upepSorfPoAfterUpdateHooks, upepSorfPoHook)
	case boil.AfterDeleteHook:
		upepSorfPoAfterDeleteHooks = append(upepSorfPoAfterDeleteHooks, upepSorfPoHook)
	case boil.AfterUpsertHook:
		upepSorfPoAfterUpsertHooks = append(upepSorfPoAfterUpsertHooks, upepSorfPoHook)
	}
}

// OneP returns a single upepSorfPo record from the query, and panics on error.
func (q upepSorfPoQuery) OneP() *UpepSorfPo {
	o, err := q.One()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return o
}

// One returns a single upepSorfPo record from the query.
func (q upepSorfPoQuery) One() (*UpepSorfPo, error) {
	o := &UpepSorfPo{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(o)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for upep_sorf_pos")
	}

	if err := o.doAfterSelectHooks(queries.GetExecutor(q.Query)); err != nil {
		return o, err
	}

	return o, nil
}

// AllP returns all UpepSorfPo records from the query, and panics on error.
func (q upepSorfPoQuery) AllP() UpepSorfPoSlice {
	o, err := q.All()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return o
}

// All returns all UpepSorfPo records from the query.
func (q upepSorfPoQuery) All() (UpepSorfPoSlice, error) {
	var o []*UpepSorfPo

	err := q.Bind(&o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to UpepSorfPo slice")
	}

	if len(upepSorfPoAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(queries.GetExecutor(q.Query)); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// CountP returns the count of all UpepSorfPo records in the query, and panics on error.
func (q upepSorfPoQuery) CountP() int64 {
	c, err := q.Count()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return c
}

// Count returns the count of all UpepSorfPo records in the query.
func (q upepSorfPoQuery) Count() (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRow().Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count upep_sorf_pos rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table, and panics on error.
func (q upepSorfPoQuery) ExistsP() bool {
	e, err := q.Exists()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}

// Exists checks if the row exists in the table.
func (q upepSorfPoQuery) Exists() (bool, error) {
	var count int64

	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRow().Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if upep_sorf_pos exists")
	}

	return count > 0, nil
}

// RefSeqEntryG pointed to by the foreign key.
func (o *UpepSorfPo) RefSeqEntryG(mods ...qm.QueryMod) upepRefSeqEntryQuery {
	return o.RefSeqEntry(boil.GetDB(), mods...)
}

// RefSeqEntry pointed to by the foreign key.
func (o *UpepSorfPo) RefSeqEntry(exec boil.Executor, mods ...qm.QueryMod) upepRefSeqEntryQuery {
	queryMods := []qm.QueryMod{
		qm.Where("id=?", o.RefSeqEntryID),
	}

	queryMods = append(queryMods, mods...)

	query := UpepRefSeqEntries(exec, queryMods...)
	queries.SetFrom(query.Query, "\"upep\".\"upep_ref_seq_entries\"")

	return query
}

// StartingCodonG pointed to by the foreign key.
func (o *UpepSorfPo) StartingCodonG(mods ...qm.QueryMod) upepCodonQuery {
	return o.StartingCodon(boil.GetDB(), mods...)
}

// StartingCodon pointed to by the foreign key.
func (o *UpepSorfPo) StartingCodon(exec boil.Executor, mods ...qm.QueryMod) upepCodonQuery {
	queryMods := []qm.QueryMod{
		qm.Where("id=?", o.StartingCodonID),
	}

	queryMods = append(queryMods, mods...)

	query := UpepCodons(exec, queryMods...)
	queries.SetFrom(query.Query, "\"upep\".\"upep_codon\"")

	return query
}

// EndingCodonG pointed to by the foreign key.
func (o *UpepSorfPo) EndingCodonG(mods ...qm.QueryMod) upepCodonQuery {
	return o.EndingCodon(boil.GetDB(), mods...)
}

// EndingCodon pointed to by the foreign key.
func (o *UpepSorfPo) EndingCodon(exec boil.Executor, mods ...qm.QueryMod) upepCodonQuery {
	queryMods := []qm.QueryMod{
		qm.Where("id=?", o.EndingCodonID),
	}

	queryMods = append(queryMods, mods...)

	query := UpepCodons(exec, queryMods...)
	queries.SetFrom(query.Query, "\"upep\".\"upep_codon\"")

	return query
} // LoadRefSeqEntry allows an eager lookup of values, cached into the
// loaded structs of the objects.
func (upepSorfPoL) LoadRefSeqEntry(e boil.Executor, singular bool, maybeUpepSorfPo interface{}) error {
	var slice []*UpepSorfPo
	var object *UpepSorfPo

	count := 1
	if singular {
		object = maybeUpepSorfPo.(*UpepSorfPo)
	} else {
		slice = *maybeUpepSorfPo.(*[]*UpepSorfPo)
		count = len(slice)
	}

	args := make([]interface{}, count)
	if singular {
		if object.R == nil {
			object.R = &upepSorfPoR{}
		}
		args[0] = object.RefSeqEntryID
	} else {
		for i, obj := range slice {
			if obj.R == nil {
				obj.R = &upepSorfPoR{}
			}
			args[i] = obj.RefSeqEntryID
		}
	}

	query := fmt.Sprintf(
		"select * from \"upep\".\"upep_ref_seq_entries\" where \"id\" in (%s)",
		strmangle.Placeholders(dialect.IndexPlaceholders, count, 1, 1),
	)

	if boil.DebugMode {
		fmt.Fprintf(boil.DebugWriter, "%s\n%v\n", query, args)
	}

	results, err := e.Query(query, args...)
	if err != nil {
		return errors.Wrap(err, "failed to eager load UpepRefSeqEntry")
	}
	defer results.Close()

	var resultSlice []*UpepRefSeqEntry
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice UpepRefSeqEntry")
	}

	if len(upepSorfPoAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		object.R.RefSeqEntry = resultSlice[0]
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.RefSeqEntryID == foreign.ID {
				local.R.RefSeqEntry = foreign
				break
			}
		}
	}

	return nil
}

// LoadStartingCodon allows an eager lookup of values, cached into the
// loaded structs of the objects.
func (upepSorfPoL) LoadStartingCodon(e boil.Executor, singular bool, maybeUpepSorfPo interface{}) error {
	var slice []*UpepSorfPo
	var object *UpepSorfPo

	count := 1
	if singular {
		object = maybeUpepSorfPo.(*UpepSorfPo)
	} else {
		slice = *maybeUpepSorfPo.(*[]*UpepSorfPo)
		count = len(slice)
	}

	args := make([]interface{}, count)
	if singular {
		if object.R == nil {
			object.R = &upepSorfPoR{}
		}
		args[0] = object.StartingCodonID
	} else {
		for i, obj := range slice {
			if obj.R == nil {
				obj.R = &upepSorfPoR{}
			}
			args[i] = obj.StartingCodonID
		}
	}

	query := fmt.Sprintf(
		"select * from \"upep\".\"upep_codon\" where \"id\" in (%s)",
		strmangle.Placeholders(dialect.IndexPlaceholders, count, 1, 1),
	)

	if boil.DebugMode {
		fmt.Fprintf(boil.DebugWriter, "%s\n%v\n", query, args)
	}

	results, err := e.Query(query, args...)
	if err != nil {
		return errors.Wrap(err, "failed to eager load UpepCodon")
	}
	defer results.Close()

	var resultSlice []*UpepCodon
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice UpepCodon")
	}

	if len(upepSorfPoAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		object.R.StartingCodon = resultSlice[0]
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.StartingCodonID == foreign.ID {
				local.R.StartingCodon = foreign
				break
			}
		}
	}

	return nil
}

// LoadEndingCodon allows an eager lookup of values, cached into the
// loaded structs of the objects.
func (upepSorfPoL) LoadEndingCodon(e boil.Executor, singular bool, maybeUpepSorfPo interface{}) error {
	var slice []*UpepSorfPo
	var object *UpepSorfPo

	count := 1
	if singular {
		object = maybeUpepSorfPo.(*UpepSorfPo)
	} else {
		slice = *maybeUpepSorfPo.(*[]*UpepSorfPo)
		count = len(slice)
	}

	args := make([]interface{}, count)
	if singular {
		if object.R == nil {
			object.R = &upepSorfPoR{}
		}
		args[0] = object.EndingCodonID
	} else {
		for i, obj := range slice {
			if obj.R == nil {
				obj.R = &upepSorfPoR{}
			}
			args[i] = obj.EndingCodonID
		}
	}

	query := fmt.Sprintf(
		"select * from \"upep\".\"upep_codon\" where \"id\" in (%s)",
		strmangle.Placeholders(dialect.IndexPlaceholders, count, 1, 1),
	)

	if boil.DebugMode {
		fmt.Fprintf(boil.DebugWriter, "%s\n%v\n", query, args)
	}

	results, err := e.Query(query, args...)
	if err != nil {
		return errors.Wrap(err, "failed to eager load UpepCodon")
	}
	defer results.Close()

	var resultSlice []*UpepCodon
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice UpepCodon")
	}

	if len(upepSorfPoAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		object.R.EndingCodon = resultSlice[0]
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.EndingCodonID == foreign.ID {
				local.R.EndingCodon = foreign
				break
			}
		}
	}

	return nil
}

// SetRefSeqEntryG of the upep_sorf_po to the related item.
// Sets o.R.RefSeqEntry to related.
// Adds o to related.R.RefSeqEntryUpepSorfPos.
// Uses the global database handle.
func (o *UpepSorfPo) SetRefSeqEntryG(insert bool, related *UpepRefSeqEntry) error {
	return o.SetRefSeqEntry(boil.GetDB(), insert, related)
}

// SetRefSeqEntryP of the upep_sorf_po to the related item.
// Sets o.R.RefSeqEntry to related.
// Adds o to related.R.RefSeqEntryUpepSorfPos.
// Panics on error.
func (o *UpepSorfPo) SetRefSeqEntryP(exec boil.Executor, insert bool, related *UpepRefSeqEntry) {
	if err := o.SetRefSeqEntry(exec, insert, related); err != nil {
		panic(boil.WrapErr(err))
	}
}

// SetRefSeqEntryGP of the upep_sorf_po to the related item.
// Sets o.R.RefSeqEntry to related.
// Adds o to related.R.RefSeqEntryUpepSorfPos.
// Uses the global database handle and panics on error.
func (o *UpepSorfPo) SetRefSeqEntryGP(insert bool, related *UpepRefSeqEntry) {
	if err := o.SetRefSeqEntry(boil.GetDB(), insert, related); err != nil {
		panic(boil.WrapErr(err))
	}
}

// SetRefSeqEntry of the upep_sorf_po to the related item.
// Sets o.R.RefSeqEntry to related.
// Adds o to related.R.RefSeqEntryUpepSorfPos.
func (o *UpepSorfPo) SetRefSeqEntry(exec boil.Executor, insert bool, related *UpepRefSeqEntry) error {
	var err error
	if insert {
		if err = related.Insert(exec); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"upep\".\"upep_sorf_pos\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"ref_seq_entry_id"}),
		strmangle.WhereClause("\"", "\"", 2, upepSorfPoPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, updateQuery)
		fmt.Fprintln(boil.DebugWriter, values)
	}

	if _, err = exec.Exec(updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.RefSeqEntryID = related.ID

	if o.R == nil {
		o.R = &upepSorfPoR{
			RefSeqEntry: related,
		}
	} else {
		o.R.RefSeqEntry = related
	}

	if related.R == nil {
		related.R = &upepRefSeqEntryR{
			RefSeqEntryUpepSorfPos: UpepSorfPoSlice{o},
		}
	} else {
		related.R.RefSeqEntryUpepSorfPos = append(related.R.RefSeqEntryUpepSorfPos, o)
	}

	return nil
}

// SetStartingCodonG of the upep_sorf_po to the related item.
// Sets o.R.StartingCodon to related.
// Adds o to related.R.StartingCodonUpepSorfPos.
// Uses the global database handle.
func (o *UpepSorfPo) SetStartingCodonG(insert bool, related *UpepCodon) error {
	return o.SetStartingCodon(boil.GetDB(), insert, related)
}

// SetStartingCodonP of the upep_sorf_po to the related item.
// Sets o.R.StartingCodon to related.
// Adds o to related.R.StartingCodonUpepSorfPos.
// Panics on error.
func (o *UpepSorfPo) SetStartingCodonP(exec boil.Executor, insert bool, related *UpepCodon) {
	if err := o.SetStartingCodon(exec, insert, related); err != nil {
		panic(boil.WrapErr(err))
	}
}

// SetStartingCodonGP of the upep_sorf_po to the related item.
// Sets o.R.StartingCodon to related.
// Adds o to related.R.StartingCodonUpepSorfPos.
// Uses the global database handle and panics on error.
func (o *UpepSorfPo) SetStartingCodonGP(insert bool, related *UpepCodon) {
	if err := o.SetStartingCodon(boil.GetDB(), insert, related); err != nil {
		panic(boil.WrapErr(err))
	}
}

// SetStartingCodon of the upep_sorf_po to the related item.
// Sets o.R.StartingCodon to related.
// Adds o to related.R.StartingCodonUpepSorfPos.
func (o *UpepSorfPo) SetStartingCodon(exec boil.Executor, insert bool, related *UpepCodon) error {
	var err error
	if insert {
		if err = related.Insert(exec); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"upep\".\"upep_sorf_pos\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"starting_codon_id"}),
		strmangle.WhereClause("\"", "\"", 2, upepSorfPoPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, updateQuery)
		fmt.Fprintln(boil.DebugWriter, values)
	}

	if _, err = exec.Exec(updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.StartingCodonID = related.ID

	if o.R == nil {
		o.R = &upepSorfPoR{
			StartingCodon: related,
		}
	} else {
		o.R.StartingCodon = related
	}

	if related.R == nil {
		related.R = &upepCodonR{
			StartingCodonUpepSorfPos: UpepSorfPoSlice{o},
		}
	} else {
		related.R.StartingCodonUpepSorfPos = append(related.R.StartingCodonUpepSorfPos, o)
	}

	return nil
}

// SetEndingCodonG of the upep_sorf_po to the related item.
// Sets o.R.EndingCodon to related.
// Adds o to related.R.EndingCodonUpepSorfPos.
// Uses the global database handle.
func (o *UpepSorfPo) SetEndingCodonG(insert bool, related *UpepCodon) error {
	return o.SetEndingCodon(boil.GetDB(), insert, related)
}

// SetEndingCodonP of the upep_sorf_po to the related item.
// Sets o.R.EndingCodon to related.
// Adds o to related.R.EndingCodonUpepSorfPos.
// Panics on error.
func (o *UpepSorfPo) SetEndingCodonP(exec boil.Executor, insert bool, related *UpepCodon) {
	if err := o.SetEndingCodon(exec, insert, related); err != nil {
		panic(boil.WrapErr(err))
	}
}

// SetEndingCodonGP of the upep_sorf_po to the related item.
// Sets o.R.EndingCodon to related.
// Adds o to related.R.EndingCodonUpepSorfPos.
// Uses the global database handle and panics on error.
func (o *UpepSorfPo) SetEndingCodonGP(insert bool, related *UpepCodon) {
	if err := o.SetEndingCodon(boil.GetDB(), insert, related); err != nil {
		panic(boil.WrapErr(err))
	}
}

// SetEndingCodon of the upep_sorf_po to the related item.
// Sets o.R.EndingCodon to related.
// Adds o to related.R.EndingCodonUpepSorfPos.
func (o *UpepSorfPo) SetEndingCodon(exec boil.Executor, insert bool, related *UpepCodon) error {
	var err error
	if insert {
		if err = related.Insert(exec); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"upep\".\"upep_sorf_pos\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"ending_codon_id"}),
		strmangle.WhereClause("\"", "\"", 2, upepSorfPoPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, updateQuery)
		fmt.Fprintln(boil.DebugWriter, values)
	}

	if _, err = exec.Exec(updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.EndingCodonID = related.ID

	if o.R == nil {
		o.R = &upepSorfPoR{
			EndingCodon: related,
		}
	} else {
		o.R.EndingCodon = related
	}

	if related.R == nil {
		related.R = &upepCodonR{
			EndingCodonUpepSorfPos: UpepSorfPoSlice{o},
		}
	} else {
		related.R.EndingCodonUpepSorfPos = append(related.R.EndingCodonUpepSorfPos, o)
	}

	return nil
}

// UpepSorfPosG retrieves all records.
func UpepSorfPosG(mods ...qm.QueryMod) upepSorfPoQuery {
	return UpepSorfPos(boil.GetDB(), mods...)
}

// UpepSorfPos retrieves all the records using an executor.
func UpepSorfPos(exec boil.Executor, mods ...qm.QueryMod) upepSorfPoQuery {
	mods = append(mods, qm.From("\"upep\".\"upep_sorf_pos\""))
	return upepSorfPoQuery{NewQuery(exec, mods...)}
}

// FindUpepSorfPoG retrieves a single record by ID.
func FindUpepSorfPoG(id int64, selectCols ...string) (*UpepSorfPo, error) {
	return FindUpepSorfPo(boil.GetDB(), id, selectCols...)
}

// FindUpepSorfPoGP retrieves a single record by ID, and panics on error.
func FindUpepSorfPoGP(id int64, selectCols ...string) *UpepSorfPo {
	retobj, err := FindUpepSorfPo(boil.GetDB(), id, selectCols...)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return retobj
}

// FindUpepSorfPo retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindUpepSorfPo(exec boil.Executor, id int64, selectCols ...string) (*UpepSorfPo, error) {
	upepSorfPoObj := &UpepSorfPo{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"upep\".\"upep_sorf_pos\" where \"id\"=$1", sel,
	)

	q := queries.Raw(exec, query, id)

	err := q.Bind(upepSorfPoObj)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from upep_sorf_pos")
	}

	return upepSorfPoObj, nil
}

// FindUpepSorfPoP retrieves a single record by ID with an executor, and panics on error.
func FindUpepSorfPoP(exec boil.Executor, id int64, selectCols ...string) *UpepSorfPo {
	retobj, err := FindUpepSorfPo(exec, id, selectCols...)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return retobj
}

// InsertG a single record. See Insert for whitelist behavior description.
func (o *UpepSorfPo) InsertG(whitelist ...string) error {
	return o.Insert(boil.GetDB(), whitelist...)
}

// InsertGP a single record, and panics on error. See Insert for whitelist
// behavior description.
func (o *UpepSorfPo) InsertGP(whitelist ...string) {
	if err := o.Insert(boil.GetDB(), whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// InsertP a single record using an executor, and panics on error. See Insert
// for whitelist behavior description.
func (o *UpepSorfPo) InsertP(exec boil.Executor, whitelist ...string) {
	if err := o.Insert(exec, whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Insert a single record using an executor.
// Whitelist behavior: If a whitelist is provided, only those columns supplied are inserted
// No whitelist behavior: Without a whitelist, columns are inferred by the following rules:
// - All columns without a default value are included (i.e. name, age)
// - All columns with a default, but non-zero are included (i.e. health = 75)
func (o *UpepSorfPo) Insert(exec boil.Executor, whitelist ...string) error {
	if o == nil {
		return errors.New("models: no upep_sorf_pos provided for insertion")
	}

	var err error
	currTime := time.Now().In(boil.GetLocation())

	if o.CreatedAt.Time.IsZero() {
		o.CreatedAt.Time = currTime
		o.CreatedAt.Valid = true
	}
	if o.UpdatedAt.Time.IsZero() {
		o.UpdatedAt.Time = currTime
		o.UpdatedAt.Valid = true
	}

	if err := o.doBeforeInsertHooks(exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(upepSorfPoColumnsWithDefault, o)

	key := makeCacheKey(whitelist, nzDefaults)
	upepSorfPoInsertCacheMut.RLock()
	cache, cached := upepSorfPoInsertCache[key]
	upepSorfPoInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := strmangle.InsertColumnSet(
			upepSorfPoColumns,
			upepSorfPoColumnsWithDefault,
			upepSorfPoColumnsWithoutDefault,
			nzDefaults,
			whitelist,
		)

		cache.valueMapping, err = queries.BindMapping(upepSorfPoType, upepSorfPoMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(upepSorfPoType, upepSorfPoMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"upep\".\"upep_sorf_pos\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.IndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"upep\".\"upep_sorf_pos\" DEFAULT VALUES"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		if len(wl) != 0 {
			cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRow(cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.Exec(cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into upep_sorf_pos")
	}

	if !cached {
		upepSorfPoInsertCacheMut.Lock()
		upepSorfPoInsertCache[key] = cache
		upepSorfPoInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(exec)
}

// UpdateG a single UpepSorfPo record. See Update for
// whitelist behavior description.
func (o *UpepSorfPo) UpdateG(whitelist ...string) error {
	return o.Update(boil.GetDB(), whitelist...)
}

// UpdateGP a single UpepSorfPo record.
// UpdateGP takes a whitelist of column names that should be updated.
// Panics on error. See Update for whitelist behavior description.
func (o *UpepSorfPo) UpdateGP(whitelist ...string) {
	if err := o.Update(boil.GetDB(), whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateP uses an executor to update the UpepSorfPo, and panics on error.
// See Update for whitelist behavior description.
func (o *UpepSorfPo) UpdateP(exec boil.Executor, whitelist ...string) {
	err := o.Update(exec, whitelist...)
	if err != nil {
		panic(boil.WrapErr(err))
	}
}

// Update uses an executor to update the UpepSorfPo.
// Whitelist behavior: If a whitelist is provided, only the columns given are updated.
// No whitelist behavior: Without a whitelist, columns are inferred by the following rules:
// - All columns are inferred to start with
// - All primary keys are subtracted from this set
// Update does not automatically update the record in case of default values. Use .Reload()
// to refresh the records.
func (o *UpepSorfPo) Update(exec boil.Executor, whitelist ...string) error {
	currTime := time.Now().In(boil.GetLocation())

	o.UpdatedAt.Time = currTime
	o.UpdatedAt.Valid = true

	var err error
	if err = o.doBeforeUpdateHooks(exec); err != nil {
		return err
	}
	key := makeCacheKey(whitelist, nil)
	upepSorfPoUpdateCacheMut.RLock()
	cache, cached := upepSorfPoUpdateCache[key]
	upepSorfPoUpdateCacheMut.RUnlock()

	if !cached {
		wl := strmangle.UpdateColumnSet(
			upepSorfPoColumns,
			upepSorfPoPrimaryKeyColumns,
			whitelist,
		)

		if len(whitelist) == 0 {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return errors.New("models: unable to update upep_sorf_pos, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"upep\".\"upep_sorf_pos\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, upepSorfPoPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(upepSorfPoType, upepSorfPoMapping, append(wl, upepSorfPoPrimaryKeyColumns...))
		if err != nil {
			return err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, values)
	}

	_, err = exec.Exec(cache.query, values...)
	if err != nil {
		return errors.Wrap(err, "models: unable to update upep_sorf_pos row")
	}

	if !cached {
		upepSorfPoUpdateCacheMut.Lock()
		upepSorfPoUpdateCache[key] = cache
		upepSorfPoUpdateCacheMut.Unlock()
	}

	return o.doAfterUpdateHooks(exec)
}

// UpdateAllP updates all rows with matching column names, and panics on error.
func (q upepSorfPoQuery) UpdateAllP(cols M) {
	if err := q.UpdateAll(cols); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateAll updates all rows with the specified column values.
func (q upepSorfPoQuery) UpdateAll(cols M) error {
	queries.SetUpdate(q.Query, cols)

	_, err := q.Query.Exec()
	if err != nil {
		return errors.Wrap(err, "models: unable to update all for upep_sorf_pos")
	}

	return nil
}

// UpdateAllG updates all rows with the specified column values.
func (o UpepSorfPoSlice) UpdateAllG(cols M) error {
	return o.UpdateAll(boil.GetDB(), cols)
}

// UpdateAllGP updates all rows with the specified column values, and panics on error.
func (o UpepSorfPoSlice) UpdateAllGP(cols M) {
	if err := o.UpdateAll(boil.GetDB(), cols); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateAllP updates all rows with the specified column values, and panics on error.
func (o UpepSorfPoSlice) UpdateAllP(exec boil.Executor, cols M) {
	if err := o.UpdateAll(exec, cols); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o UpepSorfPoSlice) UpdateAll(exec boil.Executor, cols M) error {
	ln := int64(len(o))
	if ln == 0 {
		return nil
	}

	if len(cols) == 0 {
		return errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), upepSorfPoPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"upep\".\"upep_sorf_pos\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, upepSorfPoPrimaryKeyColumns, len(o)))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}

	_, err := exec.Exec(sql, args...)
	if err != nil {
		return errors.Wrap(err, "models: unable to update all in upepSorfPo slice")
	}

	return nil
}

// UpsertG attempts an insert, and does an update or ignore on conflict.
func (o *UpepSorfPo) UpsertG(updateOnConflict bool, conflictColumns []string, updateColumns []string, whitelist ...string) error {
	return o.Upsert(boil.GetDB(), updateOnConflict, conflictColumns, updateColumns, whitelist...)
}

// UpsertGP attempts an insert, and does an update or ignore on conflict. Panics on error.
func (o *UpepSorfPo) UpsertGP(updateOnConflict bool, conflictColumns []string, updateColumns []string, whitelist ...string) {
	if err := o.Upsert(boil.GetDB(), updateOnConflict, conflictColumns, updateColumns, whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpsertP attempts an insert using an executor, and does an update or ignore on conflict.
// UpsertP panics on error.
func (o *UpepSorfPo) UpsertP(exec boil.Executor, updateOnConflict bool, conflictColumns []string, updateColumns []string, whitelist ...string) {
	if err := o.Upsert(exec, updateOnConflict, conflictColumns, updateColumns, whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
func (o *UpepSorfPo) Upsert(exec boil.Executor, updateOnConflict bool, conflictColumns []string, updateColumns []string, whitelist ...string) error {
	if o == nil {
		return errors.New("models: no upep_sorf_pos provided for upsert")
	}
	currTime := time.Now().In(boil.GetLocation())

	if o.CreatedAt.Time.IsZero() {
		o.CreatedAt.Time = currTime
		o.CreatedAt.Valid = true
	}
	o.UpdatedAt.Time = currTime
	o.UpdatedAt.Valid = true

	if err := o.doBeforeUpsertHooks(exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(upepSorfPoColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs postgres problems
	buf := strmangle.GetBuffer()

	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range updateColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range whitelist {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	upepSorfPoUpsertCacheMut.RLock()
	cache, cached := upepSorfPoUpsertCache[key]
	upepSorfPoUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := strmangle.InsertColumnSet(
			upepSorfPoColumns,
			upepSorfPoColumnsWithDefault,
			upepSorfPoColumnsWithoutDefault,
			nzDefaults,
			whitelist,
		)

		update := strmangle.UpdateColumnSet(
			upepSorfPoColumns,
			upepSorfPoPrimaryKeyColumns,
			updateColumns,
		)
		if len(update) == 0 {
			return errors.New("models: unable to upsert upep_sorf_pos, could not build update column list")
		}

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(upepSorfPoPrimaryKeyColumns))
			copy(conflict, upepSorfPoPrimaryKeyColumns)
		}
		cache.query = queries.BuildUpsertQueryPostgres(dialect, "\"upep\".\"upep_sorf_pos\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(upepSorfPoType, upepSorfPoMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(upepSorfPoType, upepSorfPoMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRow(cache.query, vals...).Scan(returns...)
		if err == sql.ErrNoRows {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.Exec(cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert upep_sorf_pos")
	}

	if !cached {
		upepSorfPoUpsertCacheMut.Lock()
		upepSorfPoUpsertCache[key] = cache
		upepSorfPoUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(exec)
}

// DeleteP deletes a single UpepSorfPo record with an executor.
// DeleteP will match against the primary key column to find the record to delete.
// Panics on error.
func (o *UpepSorfPo) DeleteP(exec boil.Executor) {
	if err := o.Delete(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteG deletes a single UpepSorfPo record.
// DeleteG will match against the primary key column to find the record to delete.
func (o *UpepSorfPo) DeleteG() error {
	if o == nil {
		return errors.New("models: no UpepSorfPo provided for deletion")
	}

	return o.Delete(boil.GetDB())
}

// DeleteGP deletes a single UpepSorfPo record.
// DeleteGP will match against the primary key column to find the record to delete.
// Panics on error.
func (o *UpepSorfPo) DeleteGP() {
	if err := o.DeleteG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Delete deletes a single UpepSorfPo record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *UpepSorfPo) Delete(exec boil.Executor) error {
	if o == nil {
		return errors.New("models: no UpepSorfPo provided for delete")
	}

	if err := o.doBeforeDeleteHooks(exec); err != nil {
		return err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), upepSorfPoPrimaryKeyMapping)
	sql := "DELETE FROM \"upep\".\"upep_sorf_pos\" WHERE \"id\"=$1"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}

	_, err := exec.Exec(sql, args...)
	if err != nil {
		return errors.Wrap(err, "models: unable to delete from upep_sorf_pos")
	}

	if err := o.doAfterDeleteHooks(exec); err != nil {
		return err
	}

	return nil
}

// DeleteAllP deletes all rows, and panics on error.
func (q upepSorfPoQuery) DeleteAllP() {
	if err := q.DeleteAll(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteAll deletes all matching rows.
func (q upepSorfPoQuery) DeleteAll() error {
	if q.Query == nil {
		return errors.New("models: no upepSorfPoQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	_, err := q.Query.Exec()
	if err != nil {
		return errors.Wrap(err, "models: unable to delete all from upep_sorf_pos")
	}

	return nil
}

// DeleteAllGP deletes all rows in the slice, and panics on error.
func (o UpepSorfPoSlice) DeleteAllGP() {
	if err := o.DeleteAllG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteAllG deletes all rows in the slice.
func (o UpepSorfPoSlice) DeleteAllG() error {
	if o == nil {
		return errors.New("models: no UpepSorfPo slice provided for delete all")
	}
	return o.DeleteAll(boil.GetDB())
}

// DeleteAllP deletes all rows in the slice, using an executor, and panics on error.
func (o UpepSorfPoSlice) DeleteAllP(exec boil.Executor) {
	if err := o.DeleteAll(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o UpepSorfPoSlice) DeleteAll(exec boil.Executor) error {
	if o == nil {
		return errors.New("models: no UpepSorfPo slice provided for delete all")
	}

	if len(o) == 0 {
		return nil
	}

	if len(upepSorfPoBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(exec); err != nil {
				return err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), upepSorfPoPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"upep\".\"upep_sorf_pos\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, upepSorfPoPrimaryKeyColumns, len(o))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args)
	}

	_, err := exec.Exec(sql, args...)
	if err != nil {
		return errors.Wrap(err, "models: unable to delete all from upepSorfPo slice")
	}

	if len(upepSorfPoAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(exec); err != nil {
				return err
			}
		}
	}

	return nil
}

// ReloadGP refetches the object from the database and panics on error.
func (o *UpepSorfPo) ReloadGP() {
	if err := o.ReloadG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadP refetches the object from the database with an executor. Panics on error.
func (o *UpepSorfPo) ReloadP(exec boil.Executor) {
	if err := o.Reload(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadG refetches the object from the database using the primary keys.
func (o *UpepSorfPo) ReloadG() error {
	if o == nil {
		return errors.New("models: no UpepSorfPo provided for reload")
	}

	return o.Reload(boil.GetDB())
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *UpepSorfPo) Reload(exec boil.Executor) error {
	ret, err := FindUpepSorfPo(exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAllGP refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
// Panics on error.
func (o *UpepSorfPoSlice) ReloadAllGP() {
	if err := o.ReloadAllG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadAllP refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
// Panics on error.
func (o *UpepSorfPoSlice) ReloadAllP(exec boil.Executor) {
	if err := o.ReloadAll(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadAllG refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *UpepSorfPoSlice) ReloadAllG() error {
	if o == nil {
		return errors.New("models: empty UpepSorfPoSlice provided for reload all")
	}

	return o.ReloadAll(boil.GetDB())
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *UpepSorfPoSlice) ReloadAll(exec boil.Executor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	upepSorfPos := UpepSorfPoSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), upepSorfPoPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"upep\".\"upep_sorf_pos\".* FROM \"upep\".\"upep_sorf_pos\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, upepSorfPoPrimaryKeyColumns, len(*o))

	q := queries.Raw(exec, sql, args...)

	err := q.Bind(&upepSorfPos)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in UpepSorfPoSlice")
	}

	*o = upepSorfPos

	return nil
}

// UpepSorfPoExists checks if the UpepSorfPo row exists.
func UpepSorfPoExists(exec boil.Executor, id int64) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"upep\".\"upep_sorf_pos\" where \"id\"=$1 limit 1)"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, id)
	}

	row := exec.QueryRow(sql, id)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if upep_sorf_pos exists")
	}

	return exists, nil
}

// UpepSorfPoExistsG checks if the UpepSorfPo row exists.
func UpepSorfPoExistsG(id int64) (bool, error) {
	return UpepSorfPoExists(boil.GetDB(), id)
}

// UpepSorfPoExistsGP checks if the UpepSorfPo row exists. Panics on error.
func UpepSorfPoExistsGP(id int64) bool {
	e, err := UpepSorfPoExists(boil.GetDB(), id)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}

// UpepSorfPoExistsP checks if the UpepSorfPo row exists. Panics on error.
func UpepSorfPoExistsP(exec boil.Executor, id int64) bool {
	e, err := UpepSorfPoExists(exec, id)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}
